<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('descriptions--index.object-array-block.title')" class="da-descriptions-block dac-object-array-block">
      <a-spin style="display: block" :loading="loading">
        <div class="arco-descriptions arco-descriptions-size-medium arco-descriptions-border">
          <div class="arco-descriptions-body">
            <table class="arco-descriptions-table">
              <tbody>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.object-array-block.model.attributes.object_arr') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullTable
                      :data="store.object_arr"
                      :meta="modelMetadata['object_arr']"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import type { DescData } from '@arco-design/web-vue/es/descriptions/interface';
  import { Model, get } from '@/api/modules/descriptions/index/object-array-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Desc = DescData & { dataIndex: string };

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    object_arr: {
      type: 'object',
      id: {
        type: 'int64',
        i18nKey: 'descriptions--index.object-array-block.model.attributes.object_arr.id',
      },
      name: {
        type: 'string',
        i18nKey: 'descriptions--index.object-array-block.model.attributes.object_arr.name',
      },
    },
  };

  // descriptions - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    object_arr: [],
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;

      if (model) {
        store.value = model;
      }
    } finally {
      setLoading(false);
    }
  };

  // descriptions - refresh
  const onDescriptionsRefresh = async () => {
    await fetchStore();
  };

  // descriptions - tabbable
  useTabbableViewBlock({
    viewName: 'DescriptionsIndex',
    refreshFn: onDescriptionsRefresh,
  });

  // descriptions - init
  onDescriptionsRefresh();
</script>
