<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('descriptions--index.scalar-block.title')" class="da-descriptions-block dac-scalar-block">
      <a-spin style="display: block" :loading="loading">
        <div class="arco-descriptions arco-descriptions-size-medium arco-descriptions-border">
          <div class="arco-descriptions-body">
            <table class="arco-descriptions-table">
              <tbody>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.double') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.double"
                      :meta="modelMetadata['double']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.int64') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.int64"
                      :meta="modelMetadata['int64']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.boolTrue') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.boolTrue"
                      :meta="modelMetadata['boolTrue']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.boolFalse') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.boolFalse"
                      :meta="modelMetadata['boolFalse']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.string') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.string"
                      :meta="modelMetadata['string']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.datetime') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.datetime"
                      :meta="modelMetadata['datetime']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.image') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.image"
                      :meta="modelMetadata['image']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.bool_optionals') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.bool_optionals"
                      :meta="modelMetadata['bool_optionals']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.int64_optionals') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.int64_optionals"
                      :meta="modelMetadata['int64_optionals']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('descriptions--index.scalar-block.model.attributes.string_optionals') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.string_optionals"
                      :meta="modelMetadata['string_optionals']"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import type { DescData } from '@arco-design/web-vue/es/descriptions/interface';
  import { Model, get } from '@/api/modules/descriptions/index/scalar-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Desc = DescData & { dataIndex: string };

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    double: {
      type: 'double',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.double',
    },
    int64: {
      type: 'int64',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.int64',
    },
    boolTrue: {
      type: 'bool',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.boolTrue',
    },
    boolFalse: {
      type: 'bool',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.boolFalse',
    },
    string: {
      type: 'string',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.string',
    },
    datetime: {
      type: 'datetime',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.datetime',
    },
    image: {
      type: 'image',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.image',
    },
    bool_optionals: {
      type: 'bool',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.bool_optionals',
      optionals: {
        true: {
          i18nKey: 'descriptions--index.scalar-block.model.attributes.bool_optionals.optionals.true',
        },
      },
    },
    int64_optionals: {
      type: 'int64',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.int64_optionals',
      optionals: {
        1: {
          i18nKey: 'descriptions--index.scalar-block.model.attributes.int64_optionals.optionals.1',
        },
      },
    },
    string_optionals: {
      type: 'string',
      i18nKey: 'descriptions--index.scalar-block.model.attributes.string_optionals',
      optionals: {
        str: {
          i18nKey: 'descriptions--index.scalar-block.model.attributes.string_optionals.optionals.str',
        },
      },
    },
  };

  // descriptions - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    double: undefined,
    int64: undefined,
    boolTrue: undefined,
    boolFalse: undefined,
    string: undefined,
    datetime: undefined,
    image: undefined,
    bool_optionals: undefined,
    int64_optionals: undefined,
    string_optionals: undefined,
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;

      if (model) {
        store.value = model;
      }
    } finally {
      setLoading(false);
    }
  };

  // descriptions - refresh
  const onDescriptionsRefresh = async () => {
    await fetchStore();
  };

  // descriptions - tabbable
  useTabbableViewBlock({
    viewName: 'DescriptionsIndex',
    refreshFn: onDescriptionsRefresh,
  });

  // descriptions - init
  onDescriptionsRefresh();
</script>
