<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('users--show.self-block.title')" class="dulladmin-descriptions-block">
      <a-spin style="display: block" :loading="loading">
        <div
          class="arco-descriptions arco-descriptions-size-medium arco-descriptions-border"
        >
          <div class="arco-descriptions-body">
            <table class="arco-descriptions-table">
              <tbody>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('users--show.self-block.model.attributes.id') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.id"
                      :meta="modelMetadata['id']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('users--show.self-block.model.attributes.name') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.name"
                      :meta="modelMetadata['name']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('users--show.self-block.model.attributes.username') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.username"
                      :meta="modelMetadata['username']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('users--show.self-block.model.attributes.email') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.email"
                      :meta="modelMetadata['email']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('users--show.self-block.model.attributes.address') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullDescriptions
                      :data="store.address"
                      :meta="modelMetadata['address']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('users--show.self-block.model.attributes.phone') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.phone"
                      :meta="modelMetadata['phone']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('users--show.self-block.model.attributes.website') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.website"
                      :meta="modelMetadata['website']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('users--show.self-block.model.attributes.company') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullDescriptions
                      :data="store.company"
                      :meta="modelMetadata['company']"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import type { DescData } from '@arco-design/web-vue/es/descriptions/interface';
  import { Model, get } from '@/api/modules/users/show/self-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Desc = DescData & { dataIndex: string };

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'int64',
      i18nKey: 'users--show.self-block.model.attributes.id',
    },
    name: {
      type: 'string',
      i18nKey: 'users--show.self-block.model.attributes.name',
    },
    username: {
      type: 'string',
      i18nKey: 'users--show.self-block.model.attributes.username',
    },
    email: {
      type: 'string',
      i18nKey: 'users--show.self-block.model.attributes.email',
    },
    address: {
      type: 'object',
      street: {
        type: 'string',
        i18nKey: 'users--show.self-block.model.attributes.address.street',
      },
      suite: {
        type: 'string',
        i18nKey: 'users--show.self-block.model.attributes.address.suite',
      },
      city: {
        type: 'string',
        i18nKey: 'users--show.self-block.model.attributes.address.city',
      },
      zipcode: {
        type: 'string',
        i18nKey: 'users--show.self-block.model.attributes.address.zipcode',
      },
      geo: {
        type: 'string',
        i18nKey: 'users--show.self-block.model.attributes.address.geo',
      },
    },
    phone: {
      type: 'string',
      i18nKey: 'users--show.self-block.model.attributes.phone',
    },
    website: {
      type: 'string',
      i18nKey: 'users--show.self-block.model.attributes.website',
    },
    company: {
      type: 'object',
      name: {
        type: 'string',
        i18nKey: 'users--show.self-block.model.attributes.company.name',
      },
      catchPhrase: {
        type: 'string',
        i18nKey: 'users--show.self-block.model.attributes.company.catchPhrase',
      },
      bs: {
        type: 'string',
        i18nKey: 'users--show.self-block.model.attributes.company.bs',
      },
    },
  };

  // descriptions - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    id: undefined,
    name: undefined,
    username: undefined,
    email: undefined,
    address: undefined,
    phone: undefined,
    website: undefined,
    company: undefined,
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;

      if (model) {
        store.value = model;
      }
    } finally {
      setLoading(false);
    }
  };

  // descriptions - refresh
  const onDescriptionsRefresh = async () => {
    await fetchStore();
  };

  // descriptions - tabbable
  useTabbableViewBlock({
    viewName: 'UsersShow',
    refreshFn: onDescriptionsRefresh,
  });

  // descriptions - init
  onDescriptionsRefresh();
</script>
