/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';
import {
  Pagination,
  Sorter,
} from '@/api/common';

/* Model */
export interface Model {
  id: string;
  userId: string;
  title: string;
}

/* GET /albums/index/self */
export interface ListRequest {
  pagination: Pagination;
  sorter?: Sorter;
}
export interface ListResponse {
  collection: Model[];
  pagination?: Pagination;
}
export function list(id: string, req: ListRequest) {
  return axios.get<ListResponse>(`/albums/index/self`, { params: req });
}
