/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* Model */
export interface Model {
  name: string;
  role: string;
}

/* GET /administrators/new/self */
export interface GetResponse {
  model: Model;
}
export function get(id: string) {
  return axios.get<GetResponse>(`/administrators/new/self`);
}

/* PUT /administrators/new/self */
export interface UpdateRequest {
  model: Model;
}
export interface UpdateResponse {
  model: Model;
}
export function update(id: string, req: UpdateRequest) {
  return axios.put<UpdateResponse>(`/administrators/new/self`, req);
}
