<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="container">
    <a-grid :cols="24" :row-gap="16">
      <a-grid-item :span="24">
        <SelfBlock />
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import SelfBlock from '@/views/modules/users/index/components/self-block.vue';
</script>

<style lang="less" scoped>
  .container {
    padding: 20px 20px 20px 20px;
  }
</style>
