/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';
import {
  Pagination,
  Sorter,
} from '@/api/common';

/* Model */
export interface Model {
  id: string;
  postId: string;
  name: string;
  email: string;
  body: string;
}

/* GET /comments/index/self */
export interface ListRequest {
  pagination: Pagination;
  sorter?: Sorter;
}
export interface ListResponse {
  collection: Model[];
  pagination?: Pagination;
}
export function list(id: string, req: ListRequest) {
  return axios.get<ListResponse>(`/comments/index/self`, { params: req });
}
