/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* Model */
export interface Model {
  id?: number;
  name?: string;
  username?: string;
  avatar?: string;
  email?: string;
  phone?: string;
  website?: string;
}

/* GET /users/${id}/show/self */
export interface GetResponse {
  model: Model;
}
export function get(id: string) {
  return axios.get<GetResponse>(`/users/${id}/show/self`);
}
