<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="dulladmin-view">
    <a-grid :cols="24" :row-gap="16">
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import { useTabbableView } from '@/hooks';

  useTabbableView({
    name: 'DashboardShow',
  });
</script>

<script lang="ts">
  export default {
    name: 'DashboardShow',
  };
</script>
