<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="da-view dac-dashboard-show-view">
    <a-grid class="da-view-grid" :cols='24' :col-gap="16" :row-gap="16">
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import { useTabbableView } from '@/hooks';

  useTabbableView({
    name: 'DashboardShow',
  });
</script>

<script lang="ts">
  export default {
    name: 'DashboardShow',
  };
</script>
