<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="container">
    <a-grid :cols="24" :row-gap="16">
      <a-grid-item :span="24">
        <SelfBlock />
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import SelfBlock from '@/views/modules/administrators/new/components/self-block.vue';
</script>

<script lang="ts">
  export default {
    name: 'AdministratorsNew',
  };
</script>

<style lang="less" scoped>
  .container {
    padding: 0 20px;
  }
</style>
