<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('dashboard--show.period-block.title')" class="da-echarts-block dac-period-block">
      <a-spin style="display: block" :loading="loading">
        <Chart :option="store" />
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { useRoute } from 'vue-router';
  import { ChartModel, get } from '@/api/modules/dashboard/show/period-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';
  import { Chart } from '@/components';

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // echarts - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<ChartModel>({});
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { chart } = data;

      if (chart) {
        store.value = chart;
      }
    } finally {
      setLoading(false);
    }
  };

  // echarts - refresh
  const onEChartsRefresh = async () => {
    await fetchStore();
  };

  // echarts - tabbable
  useTabbableViewBlock({
    viewName: 'DashboardShow',
    refreshFn: onEChartsRefresh,
  });

  // echarts - init
  onEChartsRefresh();
</script>
