<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="da-view dac-charts-index-view">
    <a-grid class="da-view-grid" :cols='24' :col-gap="16" :row-gap="16">
      <a-grid-item class="da-view-grid-item dac-basic-line-view-grid-item" :span='{"xs":24,"sm":12}'>
        <div>
          <BasicLineBlock />
        </div>
      </a-grid-item>
      <a-grid-item class="da-view-grid-item dac-stacked-line-view-grid-item" :span='{"xs":24,"sm":12}'>
        <div>
          <StackedLineBlock />
        </div>
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import { useTabbableView } from '@/hooks';
  import BasicLineBlock from '@/views/modules/charts/index/components/basic-line-block.vue';
  import StackedLineBlock from '@/views/modules/charts/index/components/stacked-line-block.vue';

  useTabbableView({
    name: 'ChartsIndex',
  });
</script>

<script lang="ts">
  export default {
    name: 'ChartsIndex',
  };
</script>
