<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="dulladmin-view">
    <a-grid :cols="24" :row-gap="16">
      <a-grid-item :span="24">
        <div
        >
          <BasicLineBlock />
        </div>
      </a-grid-item>
      <a-grid-item :span="24">
        <div
        >
          <StackedLineBlock />
        </div>
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import { useTabbableView } from '@/hooks';
  import BasicLineBlock from '@/views/modules/charts/index/components/basic-line-block.vue';
  import StackedLineBlock from '@/views/modules/charts/index/components/stacked-line-block.vue';

  useTabbableView({
    name: 'ChartsIndex',
  });
</script>

<script lang="ts">
  export default {
    name: 'ChartsIndex',
  };
</script>
