<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card>
      <a-row style="margin-bottom: 16px">
        <a-col
          style="display: flex; align-items: center; justify-content: end"
          :span="24"
        >
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh"
              ><icon-refresh size="18"
            /></div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div
                    v-for="(item, index) in tableColumnsWithShow"
                    :key="item.dataIndex"
                  >
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="
                          handleTableColumnsShowChange(
                            $event,
                            item as TableColumnData,
                            index
                          )
                        "
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
      >
        <template #postId="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelInfo[column.dataIndex]"
          />
        </template>
        <template #id="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelInfo[column.dataIndex]"
          />
        </template>
        <template #name="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelInfo[column.dataIndex]"
          />
        </template>
        <template #email="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelInfo[column.dataIndex]"
          />
        </template>
        <template #body="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelInfo[column.dataIndex]"
          />
        </template>
      </a-table>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import cloneDeep from 'lodash/cloneDeep';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/comments/index/self';
  import SimpleData from '@/components/renderer/data/simple_data.vue';
  import SimpleList from '@/components/renderer/data/simple_list.vue';
  import SimpleDescriptions from '@/components/renderer/data/simple_descriptions.vue';
  import SimpleTable from '@/components/renderer/data/simple_table.vue';
  import { useLoading } from '@/hooks';

  // types
  type Column = TableColumnData & { show?: true };
  type Pagination = Record<string, any>;

  // model info
  const modelInfo: { [key: string]: any } = {
    postId: {
      type: 'string',
    },
    id: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    email: {
      type: 'string',
    },
    body: {
      type: 'string',
    },
  };

  // route info
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // pagination info
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    showTotal: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // tableColumns definition
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => [
    {
      title: 'PostId',
      dataIndex: 'postId',
      slotName: 'postId',
    },
    {
      title: 'Id',
      dataIndex: 'id',
      slotName: 'id',
    },
    {
      title: 'Name',
      dataIndex: 'name',
      slotName: 'name',
    },
    {
      title: 'Email',
      dataIndex: 'email',
      slotName: 'email',
    },
    {
      title: 'Body',
      dataIndex: 'body',
      slotName: 'body',
    },
  ]);

  // tableColumns initialize
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = true;
      });
      tableColumnsShow.value = cloneDeep(tableColumnsWithShow.value);
    },
    { deep: true, immediate: true }
  );

  // tableColumns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    if (checked) {
      tableColumnsShow.value.splice(index, 0, column);
    } else {
      tableColumnsShow.value = tableColumnsShow.value.filter(
        (item) => item.dataIndex !== column.dataIndex
      );
    }
  };

  // tableData definition
  const { loading, setLoading } = useLoading(true);
  const tableData = ref<Model[]>([]);
  const fetchTableData = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;
      tableData.value = collection;

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = null;
        tablePagination.hideOnSinglePage = true;
      }
    } catch (_) {
      // .
    } finally {
      setLoading(false);
    }
  };

  // table - refresh
  const onTableRefresh = async () => {
    const req = { pagination: apiPagination(tablePagination) };
    await fetchTableData(req);
  };

  // table - page-change
  const onTablePageChange = async (current: number) => {
    const req = {
      pagination: { ...apiPagination(tablePagination), current },
    };
    await fetchTableData(req);
  };

  // table - init
  onTableRefresh();
</script>

<style lang="less" scoped>
  .action-icon {
    margin-left: 12px;
    cursor: pointer;
  }
</style>
