<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="dulladmin-descriptions-block">
    <a-card :title="$t('todos--show.self-block.title')">
      <a-spin style="display: block" :loading="loading">
        <div
          class="arco-descriptions arco-descriptions-size-medium arco-descriptions-border"
        >
          <div class="arco-descriptions-body">
            <table class="arco-descriptions-table">
              <tbody>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('todos--show.self-block.model.attributes.userId') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.userId"
                      :meta="modelMetadata['userId']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('todos--show.self-block.model.attributes.title') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.title"
                      :meta="modelMetadata['title']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('todos--show.self-block.model.attributes.completed') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.completed"
                      :meta="modelMetadata['completed']"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import type { DescData } from '@arco-design/web-vue/es/descriptions/interface';
  import { Model, get } from '@/api/modules/todos/show/self-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Desc = DescData & { dataIndex: string };

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    userId: {
      type: 'int64',
      i18nKey: 'todos--show.self-block.model.attributes.userId',
    },
    title: {
      type: 'string',
      i18nKey: 'todos--show.self-block.model.attributes.title',
    },
    completed: {
      type: 'bool',
      i18nKey: 'todos--show.self-block.model.attributes.completed',
      optionals: {
        true: {
          i18nKey: 'todos--show.self-block.model.attributes.completed.optionals.true',
        },
        false: {
          i18nKey: 'todos--show.self-block.model.attributes.completed.optionals.false',
        },
      },
    },
  };

  // descriptions - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    userId: undefined,
    title: undefined,
    completed: undefined,
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;

      if (model) {
        store.value = model;
      }
    } finally {
      setLoading(false);
    }
  };

  // descriptions - refresh
  const onDescriptionsRefresh = async () => {
    await fetchStore();
  };

  // descriptions - tabbable
  useTabbableViewBlock({
    viewName: 'TodosShow',
    refreshFn: onDescriptionsRefresh,
  });

  // descriptions - init
  onDescriptionsRefresh();
</script>
