menu:
  items:
    - name: 'users_management'
      icon: 'icon_user_group'
      items:
        - { name: 'users' , icon: 'icon_user_group', view: 'users#index'  }
        - { name: 'albums', icon: 'icon_folder'    , view: 'albums#index' }
        - { name: 'photos', icon: 'icon_image'     , view: 'photos#index' }
    - name: 'posts_management'
      icon: 'icon_file'
      items:
        - { name: 'posts'   , icon: 'icon_file' , view: 'posts#index'    }
        - { name: 'comments', icon: 'icon_reply', view: 'comments#index' }
    - name: 'todos_management'
      icon: 'icon_list'
      items:
        - { name: 'todos', icon: 'icon_list', view: 'todos#index' }
    - name: 'system_management'
      icon: 'icon_settings'
      items:
        - { name: 'administrators', icon: 'icon_user_group', view: 'administrators#index' }
