<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('todos--index.self-block.title')" class="da-table-block dac-self-block">
      <a-row style="margin-bottom: 16px">
        <!-- Table Collection Operations -->
        <a-col :span="12">
          <a-space>
            <a-button
              type="primary"
              @click="goto({ name: 'TodosNew' })"
            >
              <template #icon>
                <icon-plus />
              </template>
              {{ $t('table.actions.new') }}
            </a-button>
          </a-space>
        </a-col>

        <!-- Table Search/Refresh/ColumnsSetting -->
        <a-col style="display: flex; align-items: center; justify-content: end" :span="12">
          <a-space>
            <a-tag
              v-for="(value, name) in tableSearchCondition"
              :key="name"
              :visible="!!value"
              color="arcoblue"
              size="small"
              closable
              @close="handleSearchConditionClose(name as string)"
            >
              {{ t(searchMetadata[name]['i18nKey']) }}
              "{{ searchMetadata[name].optionals?.[value] ? t(searchMetadata[name].optionals[value]['i18nKey']) : value }}"
            </a-tag>
            <div
              v-show="tableSearchConditionCount"
              style="cursor: pointer"
              @click="handleSearchConditionClose('')"
            >
              <a-tag color="orangered" size="small">
                {{ t('table.actions.clearSearch') }}
              </a-tag>
            </div>
          </a-space>
          <a-tooltip :content="$t('table.actions.search')">
            <div class="action-icon" @click="handleSearchModalVisible">
              <a-badge
                color="arcoblue"
                dot
                :dot-style="{ width: '8px', height: '8px' }"
                :count="tableSearchConditionCount"
              >
                <icon-find-replace size="18"/>
              </a-badge>
            </div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh">
              <icon-refresh size="18"/>
            </div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div v-for="(item, index) in tableColumnsWithShow" :key="item.dataIndex">
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="handleTableColumnsShowChange($event, item as TableColumnData, index)"
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>

      <!-- Table -->
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
        @sorter-change="onTableSorterChange"
      >
        <template #id="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #userId="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #title="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #completed="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <!-- Table Model Operations -->
        <template #tableOperationsColumn="{ record, column }">
          <a-space>
            <a-button
              type="outline"
              status="success"
              size="small"
              @click="goto({ name: 'TodosShow', params: { id: record.id } })"
            >
              {{ $t('table.actions.show') }}
            </a-button>
            <a-button
              type="outline"
              status="warning"
              size="small"
              @click="goto({ name: 'TodosEdit', params: { id: record.id } })"
            >
              {{ $t('table.actions.edit') }}
            </a-button>
            <a-button
              v-permission="['admin', ]"
              type="outline"
              status="danger"
              size="small"
              @click="goto({ name: 'TodosDelete', params: { id: record.id } })"
            >
              {{ $t('table.actions.delete') }}
            </a-button>
            <a-button
              type="outline"
              size="small"
              @click="handleTableOperationSelfBlockShowTitleDialogVisible({ id: record.id })"
            >
              {{ $t('todos--index.self-block.actions.show-title') }}
            </a-button>
            <a-button
              type="outline"
              size="small"
              @click="handleTableOperationSelfBlockEditTitleDialogVisible({ id: record.id })"
            >
              {{ $t('todos--index.self-block.actions.edit-title') }}
            </a-button>
            <a-button
              type="outline"
              size="small"
              @click="handleTableOperationSelfBlockCreateCompletedDialogVisible({ id: record.id })"
            >
              {{ $t('todos--index.self-block.actions.create-completed') }}
            </a-button>
            <a-button
              type="outline"
              size="small"
              @click="handleTableOperationSelfBlockDeleteCompletedDialogVisible({ id: record.id })"
            >
              {{ $t('todos--index.self-block.actions.delete-completed') }}
            </a-button>
          </a-space>
        </template>
      </a-table>
    </a-card>

    <!-- Table Search -->
    <a-modal
      v-model:visible="searchModalVisible"
      class="da-form-dialog"
      :ok-text="$t('table.actions.search')"
      :on-before-ok="handleSearchModalBeforeOk"
      @cancel="handleSearchModalCancel"
    >
      <template #title>
        {{ $t('todos--index.self-block.title') }}
        -
        {{ $t('table.actions.search') }}
      </template>
      <a-form :model="tableSearchForm" :auto-label-width="true">
        <DullFormItem
          v-model="tableSearchForm.userId_eq"
          :meta="searchMetadata.userId_eq"
        />
        <DullFormItem
          v-model="tableSearchForm.completed_eq"
          :meta="searchMetadata.completed_eq"
        />
      </a-form>
    </a-modal>

    <!-- Table Model Operations UI indicator -->
    <div v-show="false" ref="tableOperationsColumnRenderableRef">
      <span />
      <span />
      <span v-permission="['admin', ]"/>
      <span />
      <span />
      <span />
      <span />
    </div>

    <!-- Table Collection/Model Operations - show_title -->
    <SelfBlockShowTitleDialog
      :id="tableOperationSelfBlockShowTitleDialogSelectedRecordID"
      v-model:visible="tableOperationSelfBlockShowTitleDialogVisible"
      :ok-callback="handleTableOperationSelfBlockShowTitleDialogOkCallback"
    />

    <!-- Table Collection/Model Operations - edit_title -->
    <SelfBlockEditTitleDialog
      :id="tableOperationSelfBlockEditTitleDialogSelectedRecordID"
      v-model:visible="tableOperationSelfBlockEditTitleDialogVisible"
      :ok-callback="handleTableOperationSelfBlockEditTitleDialogOkCallback"
    />

    <!-- Table Collection/Model Operations - create_completed -->
    <SelfBlockCreateCompletedDialog
      :id="tableOperationSelfBlockCreateCompletedDialogSelectedRecordID"
      v-model:visible="tableOperationSelfBlockCreateCompletedDialogVisible"
      :ok-callback="handleTableOperationSelfBlockCreateCompletedDialogOkCallback"
    />

    <!-- Table Collection/Model Operations - delete_completed -->
    <SelfBlockDeleteCompletedDialog
      :id="tableOperationSelfBlockDeleteCompletedDialogSelectedRecordID"
      v-model:visible="tableOperationSelfBlockDeleteCompletedDialogVisible"
      :ok-callback="handleTableOperationSelfBlockDeleteCompletedDialogOkCallback"
    />
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch, onMounted } from 'vue';
  import { useRouter, useRoute, RouteLocationRaw } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/todos/index/self-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';
  import SelfBlockShowTitleDialog from '@/views/modules/todos/index/components/self-block-show-title-dialog.vue'
  import SelfBlockEditTitleDialog from '@/views/modules/todos/index/components/self-block-edit-title-dialog.vue'
  import SelfBlockCreateCompletedDialog from '@/views/modules/todos/index/components/self-block-create-completed-dialog.vue'
  import SelfBlockDeleteCompletedDialog from '@/views/modules/todos/index/components/self-block-delete-completed-dialog.vue'

  // types
  type Column = TableColumnData & { show?: boolean, renderable?: boolean, hidden?: boolean };
  type Search = Record<string, any>;
  type Sorter = Record<string, any>;
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'int64',
      i18nKey: 'todos--index.self-block.model.attributes.id',
    },
    userId: {
      type: 'int64',
      i18nKey: 'todos--index.self-block.model.attributes.userId',
    },
    title: {
      type: 'string',
      i18nKey: 'todos--index.self-block.model.attributes.title',
    },
    completed: {
      type: 'bool',
      i18nKey: 'todos--index.self-block.model.attributes.completed',
      optionals: {
        true: {
          i18nKey: 'todos--index.self-block.model.attributes.completed.optionals.true',
        },
        false: {
          i18nKey: 'todos--index.self-block.model.attributes.completed.optionals.false',
        },
      },
    },
  };

  // search
  const searchMetadata: { [key: string]: any } = {
    userId_eq: {
      name: 'userId_eq',
      type: 'int64',
      i18nKey: 'todos--index.self-block.searchers.userId_eq',
    },
    completed_eq: {
      name: 'completed_eq',
      type: 'bool',
      i18nKey: 'todos--index.self-block.searchers.completed_eq',
      optionals: {
        true: {
          i18nKey: 'todos--index.self-block.searchers.completed_eq.optionals.true',
        },
        false: {
          i18nKey: 'todos--index.self-block.searchers.completed_eq.optionals.false',
        },
      },
    },
  };
  const baseTableSearch: Search = {
    userId_eq: null,
    completed_eq: null,
  };
  const tableSearch = reactive({
    ...baseTableSearch,
  });
  const tableSearchForm = reactive({
    ...tableSearch,
  });
  const tableSearchCondition = reactive({
    ...tableSearch,
  });
  const tableSearchConditionCount = ref(0);
  const apiSearch = (search: Search): any => {
    const o = omitBy(search, (v, k) => {
      if (searchMetadata[k].optionals) return v == null || v === '';
      return v == null || v === '' || v === false;
    });
    Object.assign(tableSearchCondition, cloneDeep(baseTableSearch), cloneDeep(o));
    tableSearchConditionCount.value = Object.keys(o).length
    return isEmpty(o) ? null : o;
  };

  // sorter
  const baseTableSorter: Sorter = {
    name: '',
    direction: '',
  };
  const tableSorter = reactive({
    ...baseTableSorter,
  });
  const apiSorter = (sorter: Sorter): any => {
    if (sorter.name === '') return null;
    return { name: sorter.name, direction: sorter.direction };
  };

  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    total: 0,
    showTotal: true,
    hideOnSinglePage: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithConfiguration = ref<Record<string, Column>>({
    id: {
      renderable: true,
    },
    userId: {
      renderable: true,
    },
    title: {
      renderable: true,
    },
    completed: {
      renderable: true,
    },
    tableOperationsColumn: {
      renderable: true,
    },
  });
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => {
    return ([
      {
        title: t('todos--index.self-block.model.attributes.id'),
        dataIndex: 'id',
        slotName: 'id',
        sortable: {
          sortDirections: ['ascend', 'descend', ],
          sorter: true,
        },
        cellClass: 'column-id',
        hidden: false,
      },
      {
        title: t('todos--index.self-block.model.attributes.userId'),
        dataIndex: 'userId',
        slotName: 'userId',
        cellClass: 'column-userId',
        hidden: false,
      },
      {
        title: t('todos--index.self-block.model.attributes.title'),
        dataIndex: 'title',
        slotName: 'title',
        cellClass: 'column-title',
        hidden: false,
      },
      {
        title: t('todos--index.self-block.model.attributes.completed'),
        dataIndex: 'completed',
        slotName: 'completed',
        cellClass: 'column-completed',
        hidden: false,
      },
      {
        title: t('table.columns.operations'),
        dataIndex: 'tableOperationsColumn',
        slotName: 'tableOperationsColumn',
        cellClass: 'column-operations',
      },
    ] as Column[]).filter((item) => {
      return tableColumnsWithConfiguration.value[item.dataIndex as string].renderable;
    });
  });
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = !item.hidden;
      });
      tableColumnsShow.value = tableColumnsWithShow.value.filter(
        (item) => item.show
      );
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    tableColumnsShow.value = tableColumnsWithShow.value.filter(
      (item) => item.show
    );
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;

      if (collection) {
        store.value = collection;
      }

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = baseTablePagination.total;;
      }
    } finally {
      setLoading(false);
    }
  };
  const updateStore = (data: Record<string, any>) => {
    const { model } = data;
    if (model) {
      const foundIndex = store.value.findIndex((e) => String(e.id) === String(model.id));
      if (foundIndex !== -1) {
        store.value.splice(foundIndex, 1, model);
      }
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - search
  const onTableSearch = async () => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(baseTablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - search condition
  const handleSearchConditionClose = async(name: string) => {
    if (name === '') {
      Object.assign(tableSearch, cloneDeep(baseTableSearch));
    } else {
      tableSearch[name] = null;
    }
    await onTableSearch();
  };

  // table - search modal
  const searchModalVisible = ref(false);
  const handleSearchModalVisible = () => {
    Object.assign(tableSearchForm, cloneDeep(tableSearch));
    searchModalVisible.value = true;
  };
  const handleSearchModalBeforeOk = async () => {
    Object.assign(tableSearch, cloneDeep(tableSearchForm));
    await onTableSearch();
    searchModalVisible.value = false;
  };
  const handleSearchModalCancel = () => {
    searchModalVisible.value = false;
  };

  // table - sorterChange
  const onTableSorterChange = async (dataIndex: string, direction: string) => {
    if (direction) {
      tableSorter.name = dataIndex;
      tableSorter.direction = direction;
    } else {
      tableSorter.name = baseTableSorter.name;
      tableSorter.direction = baseTableSorter.direction;
    }
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - operations ui
  const tableOperationsColumnRenderableRef = ref();
  onMounted(() => {
    const el = tableOperationsColumnRenderableRef.value as any;
    if (el.children.length === 0) {
      tableColumnsWithConfiguration.value.tableOperationsColumn.renderable = false
    }
  });

  // table - operations - goto
  const goto = (_route: Record<string, any>) => {
    router.push({ name: _route.name, params: _route.params, query: { back: route.path } });
  };

  // table - operations - show_title
  const tableOperationSelfBlockShowTitleDialogSelectedRecordID = ref<string>('');
  const tableOperationSelfBlockShowTitleDialogVisible = ref(false);
  const handleTableOperationSelfBlockShowTitleDialogVisible = (options: Record<string, any>) => {
    tableOperationSelfBlockShowTitleDialogSelectedRecordID.value = String(options.id ?? '');
    tableOperationSelfBlockShowTitleDialogVisible.value = true;
  };
  const handleTableOperationSelfBlockShowTitleDialogOkCallback = (options: Record<string, any>) => {
  };

  // table - operations - edit_title
  const tableOperationSelfBlockEditTitleDialogSelectedRecordID = ref<string>('');
  const tableOperationSelfBlockEditTitleDialogVisible = ref(false);
  const handleTableOperationSelfBlockEditTitleDialogVisible = (options: Record<string, any>) => {
    tableOperationSelfBlockEditTitleDialogSelectedRecordID.value = String(options.id ?? '');
    tableOperationSelfBlockEditTitleDialogVisible.value = true;
  };
  const handleTableOperationSelfBlockEditTitleDialogOkCallback = (options: Record<string, any>) => {
    const { model } = options;
    if (model) {
      updateStore({ model });
    } else {
      onTableRefresh();
    }
  };

  // table - operations - create_completed
  const tableOperationSelfBlockCreateCompletedDialogSelectedRecordID = ref<string>('');
  const tableOperationSelfBlockCreateCompletedDialogVisible = ref(false);
  const handleTableOperationSelfBlockCreateCompletedDialogVisible = (options: Record<string, any>) => {
    tableOperationSelfBlockCreateCompletedDialogSelectedRecordID.value = String(options.id ?? '');
    tableOperationSelfBlockCreateCompletedDialogVisible.value = true;
  };
  const handleTableOperationSelfBlockCreateCompletedDialogOkCallback = (options: Record<string, any>) => {
    const { model } = options;
    if (model) {
      updateStore({ model });
    } else {
      onTableRefresh();
    }
  };

  // table - operations - delete_completed
  const tableOperationSelfBlockDeleteCompletedDialogSelectedRecordID = ref<string>('');
  const tableOperationSelfBlockDeleteCompletedDialogVisible = ref(false);
  const handleTableOperationSelfBlockDeleteCompletedDialogVisible = (options: Record<string, any>) => {
    tableOperationSelfBlockDeleteCompletedDialogSelectedRecordID.value = String(options.id ?? '');
    tableOperationSelfBlockDeleteCompletedDialogVisible.value = true;
  };
  const handleTableOperationSelfBlockDeleteCompletedDialogOkCallback = (options: Record<string, any>) => {
    const { model } = options;
    if (model) {
      updateStore({ model });
    } else {
      onTableRefresh();
    }
  };

  // table - tabbable
  useTabbableViewBlock({
    viewName: 'TodosIndex',
    refreshFn: onTableRefresh,
  });

  // table - init
  onTableRefresh();
</script>
