/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* FormModel */
export interface FormModel {
  userId?: number;
  title?: string;
  completed?: boolean;
}

/* GET /todos/${id}/edit/self */
export interface GetResponse {
  form: FormModel;
}
export function get(id: string) {
  return axios.get<GetResponse>(`/todos/${id}/edit/self`);
}

/* PUT /todos/${id}/edit/self */
export interface UpdateRequest {
  form: FormModel;
}
export interface UpdateResponse {
  form: FormModel;
}
export function update(id: string, req: UpdateRequest) {
  return axios.put<UpdateResponse>(`/todos/${id}/edit/self`, req);
}
