<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card>
      <a-table> </a-table>
    </a-card>
  </div>
</template>

<script lang="ts" setup></script>

<style lang="less" scoped></style>
