<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('photos--index.self-block.title')">
      <a-row style="margin-bottom: 16px">
        <!-- Table Collection Operations -->
        <a-col :span="12">
          <a-space>
          </a-space>
        </a-col>

        <!-- Table Search/Refresh/ColumnsSetting -->
        <a-col
          style="display: flex; align-items: center; justify-content: end"
          :span="12"
        >
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh"
              ><icon-refresh size="18"
            /></div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div
                    v-for="(item, index) in tableColumnsWithShow"
                    :key="item.dataIndex"
                  >
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="
                          handleTableColumnsShowChange(
                            $event,
                            item as TableColumnData,
                            index
                          )
                        "
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>

      <!-- Table -->
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
        @sorter-change="onTableSorterChange"
      >
        <template #id="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #albumId="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #title="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #url="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #thumbnailUrl="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <!-- eslint-disable vue/no-unused-vars -->
        <!-- Table Model Operations -->
        <template #tableOperationsColumn="{ record, column }">
          <a-space>
          </a-space>
        </template>
        <!-- eslint-enable -->
      </a-table>
    </a-card>

    <!-- Table Model Operations -->
    <div v-show="false" ref="tableOperationsColumnRenderableRef">
    </div>

  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch, onMounted } from 'vue';
  import { useRouter, useRoute, RouteLocationRaw } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/photos/index/self';
  import { useLoading } from '@/hooks';

  // types
  type Column = TableColumnData & { show?: boolean, renderable?: boolean };
  type Sorter = Record<string, any>;
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'string',
      i18nKey: 'photos--index.self-block.model.attributes.id',
    },
    albumId: {
      type: 'string',
      i18nKey: 'photos--index.self-block.model.attributes.albumId',
    },
    title: {
      type: 'string',
      i18nKey: 'photos--index.self-block.model.attributes.title',
    },
    url: {
      type: 'string',
      i18nKey: 'photos--index.self-block.model.attributes.url',
    },
    thumbnailUrl: {
      type: 'string',
      i18nKey: 'photos--index.self-block.model.attributes.thumbnailUrl',
    },
  };


  // sorter
  const baseTableSorter: Sorter = {
    name: '',
    direction: '',
  };
  const tableSorter = reactive({
    ...baseTableSorter,
  });
  const apiSorter = (sorter: Sorter): any => {
    if (sorter.name === '') return null;
    return { name: sorter.name, direction: sorter.direction };
  };

  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    total: null,
    showTotal: true,
    hideOnSinglePage: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithConfiguration = ref<Record<string, Column>>({
    id: {
      renderable: true,
    },
    albumId: {
      renderable: true,
    },
    title: {
      renderable: true,
    },
    url: {
      renderable: true,
    },
    thumbnailUrl: {
      renderable: true,
    },
    tableOperationsColumn: {
      renderable: true,
    },
  });
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => {
    return ([
      {
        title: t('photos--index.self-block.model.attributes.id'),
        dataIndex: 'id',
        slotName: 'id',
        sortable: {
          sortDirections: ['ascend', 'descend', ],
          sorter: true,
        },
      },
      {
        title: t('photos--index.self-block.model.attributes.albumId'),
        dataIndex: 'albumId',
        slotName: 'albumId',
      },
      {
        title: t('photos--index.self-block.model.attributes.title'),
        dataIndex: 'title',
        slotName: 'title',
      },
      {
        title: t('photos--index.self-block.model.attributes.url'),
        dataIndex: 'url',
        slotName: 'url',
      },
      {
        title: t('photos--index.self-block.model.attributes.thumbnailUrl'),
        dataIndex: 'thumbnailUrl',
        slotName: 'thumbnailUrl',
      },
      {
        title: t('table.columns.operations'),
        dataIndex: 'tableOperationsColumn',
        slotName: 'tableOperationsColumn',
        width: 180,
      },
    ] as Column[]).filter((item) => {
      return tableColumnsWithConfiguration.value[item.dataIndex as string].renderable;
    });
  });
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = true;
      });
      tableColumnsShow.value = cloneDeep(tableColumnsWithShow.value);
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    if (checked) {
      tableColumnsShow.value.splice(index, 0, column);
    } else {
      tableColumnsShow.value = tableColumnsShow.value.filter(
        (item) => item.dataIndex !== column.dataIndex
      );
    }
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;

      if (collection) {
        store.value = collection;
      }

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = baseTablePagination.total;;
      }
    } finally {
      setLoading(false);
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      sorter: apiSorter(tableSorter),
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };


  // table - sorterChange
  const onTableSorterChange = async (dataIndex: string, direction: string) => {
    if (direction) {
      tableSorter.name = dataIndex;
      tableSorter.direction = direction;
    } else {
      tableSorter.name = baseTableSorter.name;
      tableSorter.direction = baseTableSorter.direction;
    }
    const req = omitBy({
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - operations
  const goto = (_route: Record<string, any>) => {
    router.push({ name: _route.name, params: _route.params, query: { back: route.path } });
  };

  // table - init
  onTableRefresh();

  // table - lifecycle
  const tableOperationsColumnRenderableRef = ref();
  onMounted(() => {
    const el = tableOperationsColumnRenderableRef.value as any;
    if (el.children.length === 0) {
      tableColumnsWithConfiguration.value.tableOperationsColumn.renderable = false
    }
  });
</script>

<style lang="less" scoped>
  .action-icon {
    margin-left: 12px;
    cursor: pointer;
  }
  .arco-modal {
    .arco-form {
      .arco-form-item:last-child {
        margin-bottom: 0;
      }
    }
  }
</style>
