/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';
import {
  Pagination,
  Sorter,
} from '@/api/common';

/* Model */
export interface Model {
  id: string;
  name: string;
  username: string;
  email: string;
  address: {
    street: string;
    suite: string;
    city: string;
    zipcode: string;
    geo: string;
  };
  phone: string;
  website: string;
  company: {
    name: string;
    catchPhrase: string;
    bs: string;
  };
}

/* Searcher */
interface Searcher {
  id_eq: string;
  name_cont: string;
}

/* GET /users/index/self */
export interface ListRequest {
  pagination: Pagination;
  sorter?: Sorter;
  searcher?: Searcher;
}
export interface ListResponse {
  collection: Model[];
  pagination?: Pagination;
}
export function list(id: string, req: ListRequest) {
  return axios.get<ListResponse>(`/users/index/self`, { params: req });
}
