<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="da-view dac-custom-show-view">
    <a-grid class="da-view-grid" :cols='24' :col-gap="16" :row-gap="16">
      <a-grid-item class="da-view-grid-item dac-info-view-grid-item" :span='24'>
        <div>
          <InfoBlock />
        </div>
      </a-grid-item>
      <a-grid-item class="da-view-grid-item dac-projects-view-grid-item" :span='{"xs":24,"sm":12,"md":15}'>
        <div>
          <ProjectsBlock />
        </div>
      </a-grid-item>
      <a-grid-item class="da-view-grid-item dac-teams-view-grid-item" :span='{"xs":24,"sm":12,"md":9}'>
        <div>
          <TeamsBlock />
        </div>
      </a-grid-item>
      <a-grid-item class="da-view-grid-item dac-activities-view-grid-item" :span='{"xs":24,"sm":12,"md":15}'>
        <div>
          <ActivitiesBlock />
        </div>
      </a-grid-item>
      <a-grid-item class="da-view-grid-item dac-notifications-view-grid-item" :span='{"xs":24,"sm":12,"md":9}'>
        <div>
          <NotificationsBlock />
        </div>
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import { useTabbableView } from '@/hooks';
  import InfoBlock from '@/views/modules/custom/show/components/info-block.vue';
  import ProjectsBlock from '@/views/modules/custom/show/components/projects-block.vue';
  import TeamsBlock from '@/views/modules/custom/show/components/teams-block.vue';
  import ActivitiesBlock from '@/views/modules/custom/show/components/activities-block.vue';
  import NotificationsBlock from '@/views/modules/custom/show/components/notifications-block.vue';

  useTabbableView({
    name: 'CustomShow',
  });
</script>

<script lang="ts">
  export default {
    name: 'CustomShow',
  };
</script>
