<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('albums--show.photos-block.title')" class="da-table-block dac-photos-block">
      <a-row style="margin-bottom: 16px">
        <!-- Table Collection Operations -->
        <a-col :span="12">
          <a-space>
            <a-button
              type="primary"
              @click="handleTableOperationPhotosBlockNewDialogVisible({})"
            >
              <template #icon>
                <icon-plus />
              </template>
              {{ $t('table.actions.new') }}
            </a-button>
          </a-space>
        </a-col>

        <!-- Table Search/Refresh/ColumnsSetting -->
        <a-col style="display: flex; align-items: center; justify-content: end" :span="12">
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh">
              <icon-refresh size="18"/>
            </div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div v-for="(item, index) in tableColumnsWithShow" :key="item.dataIndex">
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="handleTableColumnsShowChange($event, item as TableColumnData, index)"
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>

      <!-- Table -->
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
      >
        <template #id="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #title="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #url="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #thumbnailUrl="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <!-- Table Model Operations -->
        <template #tableOperationsColumn="{ record, column }">
          <a-space>
            <a-button
              type="outline"
              status="success"
              size="small"
              @click="handleTableOperationPhotosBlockShowDialogVisible({ id: record.id })"
            >
              {{ $t('table.actions.show') }}
            </a-button>
            <a-button
              type="outline"
              status="warning"
              size="small"
              @click="handleTableOperationPhotosBlockEditDialogVisible({ id: record.id })"
            >
              {{ $t('table.actions.edit') }}
            </a-button>
            <a-button
              type="outline"
              status="danger"
              size="small"
              @click="handleTableOperationPhotosBlockDeleteDialogVisible({ id: record.id })"
            >
              {{ $t('table.actions.delete') }}
            </a-button>
          </a-space>
        </template>
      </a-table>
    </a-card>

    <!-- Table Model Operations UI indicator -->
    <div v-show="false" ref="tableOperationsColumnRenderableRef">
      <span />
      <span />
      <span />
    </div>

    <!-- Table Collection/Model Operations - show -->
    <PhotosBlockShowDialog
      :id="tableOperationPhotosBlockShowDialogSelectedRecordID"
      v-model:visible="tableOperationPhotosBlockShowDialogVisible"
      :ok-callback="handleTableOperationPhotosBlockShowDialogOkCallback"
    />

    <!-- Table Collection/Model Operations - new -->
    <PhotosBlockNewDialog
      :id="tableOperationPhotosBlockNewDialogSelectedRecordID"
      v-model:visible="tableOperationPhotosBlockNewDialogVisible"
      :ok-callback="handleTableOperationPhotosBlockNewDialogOkCallback"
    />

    <!-- Table Collection/Model Operations - edit -->
    <PhotosBlockEditDialog
      :id="tableOperationPhotosBlockEditDialogSelectedRecordID"
      v-model:visible="tableOperationPhotosBlockEditDialogVisible"
      :ok-callback="handleTableOperationPhotosBlockEditDialogOkCallback"
    />

    <!-- Table Collection/Model Operations - delete -->
    <PhotosBlockDeleteDialog
      :id="tableOperationPhotosBlockDeleteDialogSelectedRecordID"
      v-model:visible="tableOperationPhotosBlockDeleteDialogVisible"
      :ok-callback="handleTableOperationPhotosBlockDeleteDialogOkCallback"
    />
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch, onMounted } from 'vue';
  import { useRouter, useRoute, RouteLocationRaw } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/albums/show/photos-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';
  import PhotosBlockShowDialog from '@/views/modules/albums/show/components/photos-block-show-dialog.vue'
  import PhotosBlockNewDialog from '@/views/modules/albums/show/components/photos-block-new-dialog.vue'
  import PhotosBlockEditDialog from '@/views/modules/albums/show/components/photos-block-edit-dialog.vue'
  import PhotosBlockDeleteDialog from '@/views/modules/albums/show/components/photos-block-delete-dialog.vue'

  // types
  type Column = TableColumnData & { show?: boolean, renderable?: boolean, hidden?: boolean };
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'int64',
      i18nKey: 'albums--show.photos-block.model.attributes.id',
    },
    title: {
      type: 'string',
      i18nKey: 'albums--show.photos-block.model.attributes.title',
    },
    url: {
      type: 'image',
      i18nKey: 'albums--show.photos-block.model.attributes.url',
    },
    thumbnailUrl: {
      type: 'image',
      i18nKey: 'albums--show.photos-block.model.attributes.thumbnailUrl',
    },
  };

  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 10,
    current: 1,
    total: null,
    showTotal: true,
    hideOnSinglePage: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithConfiguration = ref<Record<string, Column>>({
    id: {
      renderable: true,
    },
    title: {
      renderable: true,
    },
    url: {
      renderable: true,
    },
    thumbnailUrl: {
      renderable: true,
    },
    tableOperationsColumn: {
      renderable: true,
    },
  });
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => {
    return ([
      {
        title: t('albums--show.photos-block.model.attributes.id'),
        dataIndex: 'id',
        slotName: 'id',
        hidden: false,
      },
      {
        title: t('albums--show.photos-block.model.attributes.title'),
        dataIndex: 'title',
        slotName: 'title',
        hidden: false,
      },
      {
        title: t('albums--show.photos-block.model.attributes.url'),
        dataIndex: 'url',
        slotName: 'url',
        hidden: false,
      },
      {
        title: t('albums--show.photos-block.model.attributes.thumbnailUrl'),
        dataIndex: 'thumbnailUrl',
        slotName: 'thumbnailUrl',
        hidden: false,
      },
      {
        title: t('table.columns.operations'),
        dataIndex: 'tableOperationsColumn',
        slotName: 'tableOperationsColumn',
        width: 160,
      },
    ] as Column[]).filter((item) => {
      return tableColumnsWithConfiguration.value[item.dataIndex as string].renderable;
    });
  });
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = !item.hidden;
      });
      tableColumnsShow.value = tableColumnsWithShow.value.filter(
        (item) => item.show
      );
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    tableColumnsShow.value = tableColumnsWithShow.value.filter(
      (item) => item.show
    );
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;

      if (collection) {
        store.value = collection;
      }

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = baseTablePagination.total;;
      }
    } finally {
      setLoading(false);
    }
  };
  const updateStore = (data: Record<string, any>) => {
    const { model } = data;
    if (model) {
      const foundIndex = store.value.findIndex((e) => String(e.id) === String(model.id));
      if (foundIndex !== -1) {
        store.value.splice(foundIndex, 1, model);
      }
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - operations ui
  const tableOperationsColumnRenderableRef = ref();
  onMounted(() => {
    const el = tableOperationsColumnRenderableRef.value as any;
    if (el.children.length === 0) {
      tableColumnsWithConfiguration.value.tableOperationsColumn.renderable = false
    }
  });

  // table - operations - goto
  const goto = (_route: Record<string, any>) => {
    router.push({ name: _route.name, params: _route.params, query: { back: route.path } });
  };

  // table - operations - show
  const tableOperationPhotosBlockShowDialogSelectedRecordID = ref<string>('');
  const tableOperationPhotosBlockShowDialogVisible = ref(false);
  const handleTableOperationPhotosBlockShowDialogVisible = (options: Record<string, any>) => {
    tableOperationPhotosBlockShowDialogSelectedRecordID.value = String(options.id ?? '');
    tableOperationPhotosBlockShowDialogVisible.value = true;
  };
  const handleTableOperationPhotosBlockShowDialogOkCallback = (options: Record<string, any>) => {
  };

  // table - operations - new
  const tableOperationPhotosBlockNewDialogSelectedRecordID = ref<string>('');
  const tableOperationPhotosBlockNewDialogVisible = ref(false);
  const handleTableOperationPhotosBlockNewDialogVisible = (options: Record<string, any>) => {
    tableOperationPhotosBlockNewDialogSelectedRecordID.value = String(options.id ?? '');
    tableOperationPhotosBlockNewDialogVisible.value = true;
  };
  const handleTableOperationPhotosBlockNewDialogOkCallback = (options: Record<string, any>) => {
    const { model } = options;
    if (model) {
      updateStore({ model });
    } else {
      onTableRefresh();
    }
  };

  // table - operations - edit
  const tableOperationPhotosBlockEditDialogSelectedRecordID = ref<string>('');
  const tableOperationPhotosBlockEditDialogVisible = ref(false);
  const handleTableOperationPhotosBlockEditDialogVisible = (options: Record<string, any>) => {
    tableOperationPhotosBlockEditDialogSelectedRecordID.value = String(options.id ?? '');
    tableOperationPhotosBlockEditDialogVisible.value = true;
  };
  const handleTableOperationPhotosBlockEditDialogOkCallback = (options: Record<string, any>) => {
    const { model } = options;
    if (model) {
      updateStore({ model });
    } else {
      onTableRefresh();
    }
  };

  // table - operations - delete
  const tableOperationPhotosBlockDeleteDialogSelectedRecordID = ref<string>('');
  const tableOperationPhotosBlockDeleteDialogVisible = ref(false);
  const handleTableOperationPhotosBlockDeleteDialogVisible = (options: Record<string, any>) => {
    tableOperationPhotosBlockDeleteDialogSelectedRecordID.value = String(options.id ?? '');
    tableOperationPhotosBlockDeleteDialogVisible.value = true;
  };
  const handleTableOperationPhotosBlockDeleteDialogOkCallback = (options: Record<string, any>) => {
    const { model } = options;
    if (model) {
      updateStore({ model });
    } else {
      onTableRefresh();
    }
  };

  // table - tabbable
  useTabbableViewBlock({
    viewName: 'AlbumsShow',
    refreshFn: onTableRefresh,
  });

  // table - init
  onTableRefresh();
</script>
