<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <a-modal
    v-model:visible="visible"
    class="dulladmin-form-dialog"
    :ok-text="$t('form.actions.edit')"
    :ok-button-props="{disabled: loading}"
    :on-before-ok="handleModalBeforeOk"
    @cancel="handleModalCancel"
    @close="handleModalClose"
  >
    <template #title>
      {{ $t('albums--show.photos-block.title') }}
      -
      {{ $t('table.actions.edit') }}
      <span v-if="props.id">&nbsp;# {{ props.id }}</span>
    </template>
    <div>
      <a-spin style="display: block" :loading="loading">
        <a-form
          :model="store"
          :auto-label-width="true"
        >
          <DullFormItem
            v-model="store.title"
            :meta="modelMetadata.title"
          />
        </a-form>
      </a-spin>
    </div>
  </a-modal>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRouter, useRoute } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { omitBy } from 'lodash';
  import { Message } from '@arco-design/web-vue';
  import { FormModel, UpdateRequest, get, update } from '@/api/modules/albums/show/photos-block-edit-dialog';
  import { useLoading } from '@/hooks';

  // props
  const props = defineProps<{
    visible: boolean;
    id: string;
    okCallback: (options: Record<string, any>) => void;
  }>();
  const emits = defineEmits<{
    (e: 'update:visible', newValue: boolean): void;
  }>();

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    title: {
      type: 'string',
      hidden: false,
      i18nKey: 'albums--show.photos-block.edit-dialog.model.attributes.title',
    },
  };

  // form - model
  const baseModel: FormModel = {
    title: undefined,
  };

  // form - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<FormModel>({
    ...baseModel
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id, props.id);
      const { form } = data;

      if (form) {
        store.value = form;
      }
    } finally {
      setLoading(false);
    }
  };

  // form - save
  const { loading: saving, setLoading: setSaving } = useLoading(false);
  const onFormSave = async () => {
    setSaving(true);
    try {
      const req = {
        form: omitBy(store.value, (v) => {
          return v == null
        }),
      } as UpdateRequest;
      const { data } = await update(id, props.id, req);
      const { form } = data;

      if (form) {
        store.value = form;
      }

      Message.success(t('form.actions.edit.success'));

      const { model } = data;
      props.okCallback({ model });
    } finally {
      setSaving(false);
    }
  };

  // form - refresh
  const onFormRefresh = async () => {
    await fetchStore();
  };

  // modal - visible
  const visible = ref(false);
  watch(
    () => props.visible,
    (val) => {
      if (val) {
        visible.value = true;
        onFormRefresh();
      }
    }
  );

  // modal - ok
  const handleModalBeforeOk = async () => {
    await onFormSave();
    visible.value = false;
    emits('update:visible', false);
  };

  // modal - cancel
  const handleModalCancel = () => {
    visible.value = false;
    emits('update:visible', false);
  };

  // modal - close
  const handleModalClose = () => {
    store.value = {
      ...baseModel
    };
  };
</script>
