<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <a-modal
    class="dulladmin-descriptions-dialog"
    v-model:visible="visible"
    :on-before-ok="handleModalBeforeOk"
    @cancel="handleModalCancel"
  >
    <template #title>
      {{ $t('albums--show.photos-block.title') }}
      -
      {{ $t('table.actions.show') }}
    </template>
    <div>
      <a-spin style="display: block" :loading="loading">
        <div
          class="arco-descriptions arco-descriptions-size-medium arco-descriptions-border"
        >
          <div class="arco-descriptions-body">
            <table class="arco-descriptions-table">
              <tbody>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('albums--show.photos-block.show-dialog.model.attributes.title') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.title"
                      :meta="modelMetadata['title']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('albums--show.photos-block.show-dialog.model.attributes.url') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.url"
                      :meta="modelMetadata['url']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('albums--show.photos-block.show-dialog.model.attributes.thumbnailUrl') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.thumbnailUrl"
                      :meta="modelMetadata['thumbnailUrl']"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </a-spin>
    </div>
  </a-modal>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import type { DescData } from '@arco-design/web-vue/es/descriptions/interface';
  import { Model, get } from '@/api/modules/albums/show/photos-block-show-dialog';
  import { useLoading } from '@/hooks';

  // props
  const props = defineProps<{
    visible: boolean;
    id: string;
  }>();
  const emits = defineEmits<{
    (e: 'update:visible', newValue: boolean): void;
  }>();

  // types
  type Desc = DescData & { dataIndex: string };

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    title: {
      type: 'string',
      i18nKey: 'albums--show.photos-block.show-dialog.model.attributes.title',
    },
    url: {
      type: 'image',
      i18nKey: 'albums--show.photos-block.show-dialog.model.attributes.url',
    },
    thumbnailUrl: {
      type: 'image',
      i18nKey: 'albums--show.photos-block.show-dialog.model.attributes.thumbnailUrl',
    },
  };

  // descriptions - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    title: undefined,
    url: undefined,
    thumbnailUrl: undefined,
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id, props.id);
      const { model } = data;

      if (model) {
        store.value = model;
      }
    } finally {
      setLoading(false);
    }
  };

  // descriptions - refresh
  const onDescriptionsRefresh = async () => {
    await fetchStore();
  };

  // modal - visible
  const visible = ref(false);
  watch(
    () => props.visible,
    (val) => {
      if (val) {
        visible.value = true;
        onDescriptionsRefresh();
      }
    }
  );

  // modal - ok
  const handleModalBeforeOk = async () => {
    visible.value = false;
    emits('update:visible', false);
  };

  // modal - cancel
  const handleModalCancel = () => {
    visible.value = false;
    emits('update:visible', false);
  };
</script>
