<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('albums--show.self-block.title')">
      <a-spin style="display: block" :loading="loading">
        <div
          class="arco-descriptions arco-descriptions-size-medium arco-descriptions-border"
        >
          <div class="arco-descriptions-body">
            <table class="arco-descriptions-table">
              <tbody>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('albums--show.self-block.model.attributes.id') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.id"
                      :meta="modelMetadata['id']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('albums--show.self-block.model.attributes.userId') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.userId"
                      :meta="modelMetadata['userId']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('albums--show.self-block.model.attributes.title') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.title"
                      :meta="modelMetadata['title']"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import type { DescData } from '@arco-design/web-vue/es/descriptions/interface';
  import { Model, get } from '@/api/modules/albums/show/self';
  import { useLoading } from '@/hooks';

  // types
  type Desc = DescData & { dataIndex: string };

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'string',
      i18nKey: 'albums--show.self-block.model.attributes.id',
    },
    userId: {
      type: 'string',
      i18nKey: 'albums--show.self-block.model.attributes.userId',
    },
    title: {
      type: 'string',
      i18nKey: 'albums--show.self-block.model.attributes.title',
    },
  };

  // descriptions - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    id: null,
    userId: null,
    title: null,
  } as Model);
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;
      store.value = model;
    } catch (_) {
      // .
    } finally {
      setLoading(false);
    }
  };

  // descriptions - init
  fetchStore();
</script>

<style lang="less" scoped></style>
