<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="dulladmin-table-block">
    <a-card :title="$t('administrators--index.self-block.title')">
      <a-row style="margin-bottom: 16px">
        <!-- Table Collection Operations -->
        <a-col :span="12">
          <a-space>
            <a-button
              v-permission="['admin', ]"
              type="primary"
              @click="goto({ name: 'AdministratorsNew' })"
            >
              <template #icon>
                <icon-plus />
              </template>
              {{ $t('table.actions.new') }}
            </a-button>
          </a-space>
        </a-col>

        <!-- Table Search/Refresh/ColumnsSetting -->
        <a-col
          style="display: flex; align-items: center; justify-content: end"
          :span="12"
        >
          <a-space>
            <a-tag
              v-for="(value, name) in tableSearchCondition"
              :key="name"
              :visible="!!value"
              color="arcoblue"
              size="small"
              closable
              @close="handleSearchConditionClose(name as string)"
            >
              {{ t(searchMetadata[name]['i18nKey']) }} "{{ value }}"
            </a-tag>
            <div
              style="cursor: pointer"
              v-show="tableSearchConditionCount"
              @click="handleSearchConditionClose('')"
            >
              <a-tag color="orangered" size="small">
                {{ t('table.actions.clearSearch') }}
              </a-tag>
            </div>
          </a-space>
          <a-tooltip :content="$t('table.actions.search')">
            <div class="action-icon" @click="handleSearchModalVisible">
              <a-badge
                color="arcoblue"
                dot
                :dotStyle="{ width: '8px', height: '8px' }"
                :count="tableSearchConditionCount"
              >
                <icon-find-replace size="18"/>
              </a-badge>
            </div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh"
              ><icon-refresh size="18"
            /></div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div
                    v-for="(item, index) in tableColumnsWithShow"
                    :key="item.dataIndex"
                  >
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="
                          handleTableColumnsShowChange(
                            $event,
                            item as TableColumnData,
                            index
                          )
                        "
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>

      <!-- Table -->
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
      >
        <template #id="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #name="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #role="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <!-- eslint-disable vue/no-unused-vars -->
        <!-- Table Model Operations -->
        <template #tableOperationsColumn="{ record, column }">
          <a-space>
            <a-button
              v-permission="['admin', ]"
              type="outline"
              status="warning"
              size="small"
              @click="goto({ name: 'AdministratorsEdit', params: { id: record.id } })"
            >
              {{ $t('table.actions.edit') }}
            </a-button>
          </a-space>
        </template>
        <!-- eslint-enable -->
      </a-table>
    </a-card>

    <!-- Table Model Operations -->
    <div v-show="false" ref="tableOperationsColumnRenderableRef">
      <span
        v-permission="['admin', ]"
      />
    </div>

    <!-- Table Search -->
    <a-modal
      class="dulladmin-table-block-search-modal"
      v-model:visible="searchModalVisible"
      :okText="$t('table.actions.search')"
      :on-before-ok="handleSearchModalBeforeOk"
      @cancel="handleSearchModalCancel"
    >
      <template #title>
        {{ $t('administrators--index.self-block.title') }}
        -
        {{ $t('table.actions.search') }}
      </template>
      <a-form
        :model="tableSearchForm"
        :auto-label-width="true"
      >
        <DullFormItem
          v-model="tableSearchForm.id_eq"
          :meta="searchMetadata.id_eq"
        />
        <DullFormItem
          v-model="tableSearchForm.role_eq"
          :meta="searchMetadata.role_eq"
        />
      </a-form>
    </a-modal>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch, onMounted } from 'vue';
  import { useRouter, useRoute, RouteLocationRaw } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/administrators/index/self';
  import { useLoading } from '@/hooks';

  // types
  type Column = TableColumnData & { show?: boolean, renderable?: boolean };
  type Search = Record<string, any>;
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'string',
      i18nKey: 'administrators--index.self-block.model.attributes.id',
    },
    name: {
      type: 'string',
      i18nKey: 'administrators--index.self-block.model.attributes.name',
    },
    role: {
      type: 'string',
      i18nKey: 'administrators--index.self-block.model.attributes.role',
      optionals: {
        admin: {
          i18nKey: 'administrators--index.self-block.model.attributes.role.optionals.admin',
        },
        user: {
          i18nKey: 'administrators--index.self-block.model.attributes.role.optionals.user',
        },
      },
    },
  };

  // search
  const searchMetadata: { [key: string]: any } = {
    id_eq: {
      name: 'id_eq',
      type: 'string',
      i18nKey: 'administrators--index.self-block.searchers.id_eq',
    },
    role_eq: {
      name: 'role_eq',
      type: 'string',
      i18nKey: 'administrators--index.self-block.searchers.role_eq',
      optionals: {
        admin: {
          i18nKey: 'administrators--index.self-block.searchers.role_eq.optionals.admin',
        },
        user: {
          i18nKey: 'administrators--index.self-block.searchers.role_eq.optionals.user',
        },
      },
    },
  };
  const baseTableSearch: Search = {
    id_eq: null,
    role_eq: null,
  };
  const tableSearch = reactive({
    ...baseTableSearch,
  });
  const tableSearchForm = reactive({
    ...tableSearch,
  });
  const tableSearchCondition = reactive({
    ...tableSearch,
  });
  const tableSearchConditionCount = ref(0);
  const apiSearch = (search: Search): any => {
    const o = omitBy(search, (v, k) => {
      if (searchMetadata[k].optionals) return v == null || v === '';
      return v == null || v === '' || v === false;
    });
    Object.assign(tableSearchCondition, cloneDeep(baseTableSearch), cloneDeep(o));
    tableSearchConditionCount.value = Object.keys(o).length
    return isEmpty(o) ? null : o;
  };


  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    total: null,
    showTotal: true,
    hideOnSinglePage: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithConfiguration = ref<Record<string, Column>>({
    id: {
      renderable: true,
    },
    name: {
      renderable: true,
    },
    role: {
      renderable: true,
    },
    tableOperationsColumn: {
      renderable: true,
    },
  });
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => {
    return ([
      {
        title: t('administrators--index.self-block.model.attributes.id'),
        dataIndex: 'id',
        slotName: 'id',
      },
      {
        title: t('administrators--index.self-block.model.attributes.name'),
        dataIndex: 'name',
        slotName: 'name',
      },
      {
        title: t('administrators--index.self-block.model.attributes.role'),
        dataIndex: 'role',
        slotName: 'role',
      },
      {
        title: t('table.columns.operations'),
        dataIndex: 'tableOperationsColumn',
        slotName: 'tableOperationsColumn',
        width: 180,
      },
    ] as Column[]).filter((item) => {
      return tableColumnsWithConfiguration.value[item.dataIndex as string].renderable;
    });
  });
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = true;
      });
      tableColumnsShow.value = cloneDeep(tableColumnsWithShow.value);
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    if (checked) {
      tableColumnsShow.value.splice(index, 0, column);
    } else {
      tableColumnsShow.value = tableColumnsShow.value.filter(
        (item) => item.dataIndex !== column.dataIndex
      );
    }
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;

      if (collection) {
        store.value = collection;
      }

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = baseTablePagination.total;;
      }
    } finally {
      setLoading(false);
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - search
  const onTableSearch = async () => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      pagination: apiPagination(baseTablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - search condition
  const handleSearchConditionClose = async(name: string) => {
    if (name === '') {
      Object.assign(tableSearch, cloneDeep(baseTableSearch));
    } else {
      tableSearch[name] = null;
    }
    await onTableSearch();
  };

  // table - search modal
  const searchModalVisible = ref(false);
  const handleSearchModalVisible = () => {
    Object.assign(tableSearchForm, cloneDeep(tableSearch));
    searchModalVisible.value = true;
  };
  const handleSearchModalBeforeOk = async () => {
    Object.assign(tableSearch, cloneDeep(tableSearchForm));
    await onTableSearch();
    searchModalVisible.value = false;
  };
  const handleSearchModalCancel = () => {
    searchModalVisible.value = false;
  };


  // table - operations
  const goto = (_route: Record<string, any>) => {
    router.push({ name: _route.name, params: _route.params, query: { back: route.path } });
  };

  // table - init
  onTableRefresh();

  // table - lifecycle
  const tableOperationsColumnRenderableRef = ref();
  onMounted(() => {
    const el = tableOperationsColumnRenderableRef.value as any;
    if (el.children.length === 0) {
      tableColumnsWithConfiguration.value.tableOperationsColumn.renderable = false
    }
  });
</script>
