<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('administrators--index.self-block.title')">
      <a-row style="margin-bottom: 16px">
        <a-col :span="12">
          <a-space>
            <a-button
              v-permission="['admin', ]"
              type="primary"
              @click="goto({ name: 'AdministratorsNew' })"
            >
              <template #icon>
                <icon-plus />
              </template>
              {{ $t('table.actions.new') }}
            </a-button>
          </a-space>
        </a-col>
        <a-col
          style="display: flex; align-items: center; justify-content: end"
          :span="12"
        >
          <a-tooltip :content="$t('table.actions.search')">
            <div class="action-icon" @click="handleSearchModalVisible"
              ><icon-find-replace size="18"
            /></div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh"
              ><icon-refresh size="18"
            /></div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div
                    v-for="(item, index) in tableColumnsWithShow"
                    :key="item.dataIndex"
                  >
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="
                          handleTableColumnsShowChange(
                            $event,
                            item as TableColumnData,
                            index
                          )
                        "
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
      >
        <template #id="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #name="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #role="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <!-- eslint-disable vue/no-unused-vars -->
        <template #tableOperationsColumn="{ record, column }">
          <a-space>
            <a-button
              v-permission="['admin', ]"
              type="outline"
              status="warning"
              size="small"
              @click="goto({ name: 'AdministratorsEdit', params: { id: record.id } })"
            >
              {{ $t('table.actions.edit') }}
            </a-button>
          </a-space>
        </template>
        <!-- eslint-enable -->
      </a-table>
    </a-card>

    <a-modal
      v-model:visible="searchModalVisible"
      :okText="$t('table.actions.search')"
      @ok="handleSearchModalOk"
      @cancel="handleSearchModalCancel"
    >
      <template #title>
        {{ $t('administrators--index.self-block.title') }}
        -
        {{ $t('table.actions.search') }}
      </template>
      <a-form
        ref="searchFormRef"
        :model="tableSearch"
        :auto-label-width="true"
      >
        <DullFormItem
          v-model="tableSearch.id_eq"
          :meta="searchMetadata.id_eq"
        />
        <DullFormItem
          v-model="tableSearch.role_eq"
          :meta="searchMetadata.role_eq"
        />
      </a-form>
    </a-modal>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch } from 'vue';
  import { useRouter, useRoute, RouteLocationRaw } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import { FormInstance } from '@arco-design/web-vue/es/form';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/administrators/index/self';
  import { useLoading } from '@/hooks';

  // types
  type Column = TableColumnData & { show?: true };
  type Search = Record<string, any>;
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'string',
      i18nKey: 'administrators--index.self-block.model.attributes.id',
    },
    name: {
      type: 'string',
      i18nKey: 'administrators--index.self-block.model.attributes.name',
    },
    role: {
      type: 'string',
      i18nKey: 'administrators--index.self-block.model.attributes.role',
      optionals: {
        admin: {
          i18nKey: 'administrators--index.self-block.model.attributes.role.optionals.admin',
        },
        user: {
          i18nKey: 'administrators--index.self-block.model.attributes.role.optionals.user',
        },
      },
    },
  };

  // search
  const searchFormRef = ref<FormInstance>();
  const searchMetadata: { [key: string]: any } = {
    id_eq: {
      name: 'id_eq',
      type: 'string',
      i18nKey: 'administrators--index.self-block.searchers.id_eq',
    },
    role_eq: {
      name: 'role_eq',
      type: 'string',
      i18nKey: 'administrators--index.self-block.searchers.role_eq',
      optionals: {
        admin: {
          i18nKey: 'administrators--index.self-block.searchers.role_eq.optionals.admin',
        },
        user: {
          i18nKey: 'administrators--index.self-block.searchers.role_eq.optionals.user',
        },
      },
    },
  };
  const baseTableSearch: Search = {
    id_eq: null,
    role_eq: null,
  };
  const tableSearch = reactive({
    ...baseTableSearch,
  });
  const apiSearch = (search: Search): any => {
    const o = omitBy(search, (v, k) => {
      if (searchMetadata[k].optionals) return v == null || v === '';
      return v == null || v === '' || v === false;
    });
    return isEmpty(o) ? null : o;
  };

  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    total: null,
    showTotal: true,
    hideOnSinglePage: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => [
    {
      title: t('administrators--index.self-block.model.attributes.id'),
      dataIndex: 'id',
      slotName: 'id',
    },
    {
      title: t('administrators--index.self-block.model.attributes.name'),
      dataIndex: 'name',
      slotName: 'name',
    },
    {
      title: t('administrators--index.self-block.model.attributes.role'),
      dataIndex: 'role',
      slotName: 'role',
    },
    {
      title: t('table.columns.operations'),
      dataIndex: 'tableOperationsColumn',
      slotName: 'tableOperationsColumn',
    },
  ]);
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = true;
      });
      tableColumnsShow.value = cloneDeep(tableColumnsWithShow.value);
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    if (checked) {
      tableColumnsShow.value.splice(index, 0, column);
    } else {
      tableColumnsShow.value = tableColumnsShow.value.filter(
        (item) => item.dataIndex !== column.dataIndex
      );
    }
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;

      if (collection) {
        store.value = collection;
      }

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = baseTablePagination.total;;
      }
    } finally {
      setLoading(false);
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table -- search
  const searchModalVisible = ref(false);
  const handleSearchModalVisible = () => {
    searchModalVisible.value = true;
  };
  const handleSearchModalOk = () => {
    searchModalVisible.value = false;
    const req = omitBy({
      search: apiSearch(tableSearch),
      pagination: apiPagination(baseTablePagination),
    }, v => v == null) as ListRequest;
    fetchStore(req);
  };
  const handleSearchModalCancel = () => {
    searchModalVisible.value = false;
  };

  // table - actions
  const goto = (_route: Record<string, any>) => {
    router.push({ name: _route.name, params: _route.params, query: { back: route.path } });
  };

  // table - init
  onTableRefresh();
</script>

<style lang="less" scoped>
  .action-icon {
    margin-left: 12px;
    cursor: pointer;
  }
  .arco-modal {
    .arco-form {
      .arco-form-item:last-child {
        margin-bottom: 0;
      }
    }
  }
</style>
