<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('photos--show.self-block.title')" class="dulladmin-descriptions-block">
      <a-spin style="display: block" :loading="loading">
        <div class="arco-descriptions arco-descriptions-size-medium arco-descriptions-border">
          <div class="arco-descriptions-body">
            <table class="arco-descriptions-table">
              <tbody>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('photos--show.self-block.model.attributes.albumId') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.albumId"
                      :meta="modelMetadata['albumId']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('photos--show.self-block.model.attributes.title') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.title"
                      :meta="modelMetadata['title']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('photos--show.self-block.model.attributes.url') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.url"
                      :meta="modelMetadata['url']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('photos--show.self-block.model.attributes.thumbnailUrl') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.thumbnailUrl"
                      :meta="modelMetadata['thumbnailUrl']"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import type { DescData } from '@arco-design/web-vue/es/descriptions/interface';
  import { Model, get } from '@/api/modules/photos/show/self-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Desc = DescData & { dataIndex: string };

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    albumId: {
      type: 'int64',
      i18nKey: 'photos--show.self-block.model.attributes.albumId',
    },
    title: {
      type: 'string',
      i18nKey: 'photos--show.self-block.model.attributes.title',
    },
    url: {
      type: 'image',
      i18nKey: 'photos--show.self-block.model.attributes.url',
    },
    thumbnailUrl: {
      type: 'image',
      i18nKey: 'photos--show.self-block.model.attributes.thumbnailUrl',
    },
  };

  // descriptions - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    albumId: undefined,
    title: undefined,
    url: undefined,
    thumbnailUrl: undefined,
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;

      if (model) {
        store.value = model;
      }
    } finally {
      setLoading(false);
    }
  };

  // descriptions - refresh
  const onDescriptionsRefresh = async () => {
    await fetchStore();
  };

  // descriptions - tabbable
  useTabbableViewBlock({
    viewName: 'PhotosShow',
    refreshFn: onDescriptionsRefresh,
  });

  // descriptions - init
  onDescriptionsRefresh();
</script>
