<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="da-view dac-tables-index-view">
    <a-grid class="da-view-grid" :cols='24' :col-gap="16" :row-gap="16">
      <a-grid-item class="da-view-grid-item dac-scalar-view-grid-item" :span='24'>
        <div>
          <ScalarBlock />
        </div>
      </a-grid-item>
      <a-grid-item class="da-view-grid-item dac-scalar-array-view-grid-item" :span='24'>
        <div>
          <ScalarArrayBlock />
        </div>
      </a-grid-item>
      <a-grid-item class="da-view-grid-item dac-object-view-grid-item" :span='{"xs":24,"sm":12}'>
        <div>
          <ObjectBlock />
        </div>
      </a-grid-item>
      <a-grid-item class="da-view-grid-item dac-object-array-view-grid-item" :span='{"xs":24,"sm":12}'>
        <div>
          <ObjectArrayBlock />
        </div>
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import { useTabbableView } from '@/hooks';
  import ScalarBlock from '@/views/modules/tables/index/components/scalar-block.vue';
  import ScalarArrayBlock from '@/views/modules/tables/index/components/scalar-array-block.vue';
  import ObjectBlock from '@/views/modules/tables/index/components/object-block.vue';
  import ObjectArrayBlock from '@/views/modules/tables/index/components/object-array-block.vue';

  useTabbableView({
    name: 'TablesIndex',
  });
</script>

<script lang="ts">
  export default {
    name: 'TablesIndex',
  };
</script>
