<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="da-view dac-posts-index-view">
    <a-grid :cols="24" :col-gap="16" :row-gap="16">
      <a-grid-item :span="24">
        <div>
          <SelfBlock />
        </div>
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import { useTabbableView } from '@/hooks';
  import SelfBlock from '@/views/modules/posts/index/components/self-block.vue';

  useTabbableView({
    name: 'PostsIndex',
  });
</script>

<script lang="ts">
  export default {
    name: 'PostsIndex',
  };
</script>
