<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('albums--index.self-block.title')" class="da-table-block dac-self-block">
      <a-row style="margin-bottom: 16px">
        <!-- Table Collection Operations -->
        <a-col :span="12">
          <a-space>
          </a-space>
        </a-col>

        <!-- Table Search/Refresh/ColumnsSetting -->
        <a-col style="display: flex; align-items: center; justify-content: end" :span="12">
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh">
              <icon-refresh size="18"/>
            </div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div v-for="(item, index) in tableColumnsWithShow" :key="item.dataIndex">
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="handleTableColumnsShowChange($event, item as TableColumnData, index)"
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>

      <!-- Table -->
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
        @sorter-change="onTableSorterChange"
      >
        <template #id="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #userId="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #title="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <!-- Table Model Operations -->
        <template #tableOperationsColumn="{ record, column }">
          <a-space>
            <a-button
              type="outline"
              status="success"
              size="small"
              @click="goto({ name: 'AlbumsShow', params: { id: record.id } })"
            >
              {{ $t('table.actions.show') }}
            </a-button>
          </a-space>
        </template>
      </a-table>
    </a-card>

    <!-- Table Model Operations UI indicator -->
    <div v-show="false" ref="tableOperationsColumnRenderableRef">
      <span />
    </div>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch, onMounted } from 'vue';
  import { useRouter, useRoute, RouteLocationRaw } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/albums/index/self-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Column = TableColumnData & { show?: boolean, renderable?: boolean, hidden?: boolean };
  type Sorter = Record<string, any>;
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'int64',
      i18nKey: 'albums--index.self-block.model.attributes.id',
    },
    userId: {
      type: 'int64',
      i18nKey: 'albums--index.self-block.model.attributes.userId',
    },
    title: {
      type: 'string',
      i18nKey: 'albums--index.self-block.model.attributes.title',
    },
  };

  // sorter
  const baseTableSorter: Sorter = {
    name: '',
    direction: '',
  };
  const tableSorter = reactive({
    ...baseTableSorter,
  });
  const apiSorter = (sorter: Sorter): any => {
    if (sorter.name === '') return null;
    return { name: sorter.name, direction: sorter.direction };
  };

  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    total: null,
    showTotal: true,
    hideOnSinglePage: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithConfiguration = ref<Record<string, Column>>({
    id: {
      renderable: true,
    },
    userId: {
      renderable: true,
    },
    title: {
      renderable: true,
    },
    tableOperationsColumn: {
      renderable: true,
    },
  });
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => {
    return ([
      {
        title: t('albums--index.self-block.model.attributes.id'),
        dataIndex: 'id',
        slotName: 'id',
        sortable: {
          sortDirections: ['ascend', 'descend', ],
          sorter: true,
        },
        hidden: false,
      },
      {
        title: t('albums--index.self-block.model.attributes.userId'),
        dataIndex: 'userId',
        slotName: 'userId',
        hidden: false,
      },
      {
        title: t('albums--index.self-block.model.attributes.title'),
        dataIndex: 'title',
        slotName: 'title',
        hidden: false,
      },
      {
        title: t('table.columns.operations'),
        dataIndex: 'tableOperationsColumn',
        slotName: 'tableOperationsColumn',
        width: 160,
      },
    ] as Column[]).filter((item) => {
      return tableColumnsWithConfiguration.value[item.dataIndex as string].renderable;
    });
  });
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = !item.hidden;
      });
      tableColumnsShow.value = tableColumnsWithShow.value.filter(
        (item) => item.show
      );
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    tableColumnsShow.value = tableColumnsWithShow.value.filter(
      (item) => item.show
    );
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;

      if (collection) {
        store.value = collection;
      }

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = baseTablePagination.total;;
      }
    } finally {
      setLoading(false);
    }
  };
  const updateStore = (data: Record<string, any>) => {
    const { model } = data;
    if (model) {
      const foundIndex = store.value.findIndex((e) => String(e.id) === String(model.id));
      if (foundIndex !== -1) {
        store.value.splice(foundIndex, 1, model);
      }
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      sorter: apiSorter(tableSorter),
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - sorterChange
  const onTableSorterChange = async (dataIndex: string, direction: string) => {
    if (direction) {
      tableSorter.name = dataIndex;
      tableSorter.direction = direction;
    } else {
      tableSorter.name = baseTableSorter.name;
      tableSorter.direction = baseTableSorter.direction;
    }
    const req = omitBy({
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - operations ui
  const tableOperationsColumnRenderableRef = ref();
  onMounted(() => {
    const el = tableOperationsColumnRenderableRef.value as any;
    if (el.children.length === 0) {
      tableColumnsWithConfiguration.value.tableOperationsColumn.renderable = false
    }
  });

  // table - operations - goto
  const goto = (_route: Record<string, any>) => {
    router.push({ name: _route.name, params: _route.params, query: { back: route.path } });
  };

  // table - tabbable
  useTabbableViewBlock({
    viewName: 'AlbumsIndex',
    refreshFn: onTableRefresh,
  });

  // table - init
  onTableRefresh();
</script>
