<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('albums--index.self-block.title')">
      <a-row style="margin-bottom: 16px">
        <a-col
          style="display: flex; align-items: center; justify-content: end"
          :span="24"
        >
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh"
              ><icon-refresh size="18"
            /></div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div
                    v-for="(item, index) in tableColumnsWithShow"
                    :key="item.dataIndex"
                  >
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="
                          handleTableColumnsShowChange(
                            $event,
                            item as TableColumnData,
                            index
                          )
                        "
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
        @sorter-change="onTableSorterChange"
      >
        <template #id="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #userId="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #title="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
      </a-table>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import { FormInstance } from '@arco-design/web-vue/es/form';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/albums/index/self';
  import { useLoading } from '@/hooks';

  // types
  type Column = TableColumnData & { show?: true };
  type Sorter = Record<string, any>;
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'string',
      i18nKey: 'albums--index.self-block.model.attributes.id',
    },
    userId: {
      type: 'string',
      i18nKey: 'albums--index.self-block.model.attributes.userId',
    },
    title: {
      type: 'string',
      i18nKey: 'albums--index.self-block.model.attributes.title',
    },
  };

  // sorter
  const baseTableSorter: Sorter = {
    name: '',
    direction: '',
  };
  const tableSorter = reactive({
    ...baseTableSorter,
  });
  const apiSorter = (sorter: Sorter): any => {
    if (sorter.name === '') return null;
    return { name: sorter.name, direction: sorter.direction };
  };

  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    total: null,
    showTotal: true,
    hideOnSinglePage: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => [
    {
      title: t('albums--index.self-block.model.attributes.id'),
      dataIndex: 'id',
      slotName: 'id',
      sortable: {
        sortDirections: ['ascend', 'descend', ],
        sorter: true,
      },
    },
    {
      title: t('albums--index.self-block.model.attributes.userId'),
      dataIndex: 'userId',
      slotName: 'userId',
    },
    {
      title: t('albums--index.self-block.model.attributes.title'),
      dataIndex: 'title',
      slotName: 'title',
    },
  ]);
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = true;
      });
      tableColumnsShow.value = cloneDeep(tableColumnsWithShow.value);
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    if (checked) {
      tableColumnsShow.value.splice(index, 0, column);
    } else {
      tableColumnsShow.value = tableColumnsShow.value.filter(
        (item) => item.dataIndex !== column.dataIndex
      );
    }
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;
      store.value = collection;

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = null;
      }
    } catch (_) {
      // .
    } finally {
      setLoading(false);
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      sorter: apiSorter(tableSorter),
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - sorterChange
  const onTableSorterChange = async (dataIndex: string, direction: string) => {
    if (direction) {
      tableSorter.name = dataIndex;
      tableSorter.direction = direction;
    } else {
      tableSorter.name = baseTableSorter.name;
      tableSorter.direction = baseTableSorter.direction;
    }
    const req = omitBy({
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - init
  onTableRefresh();
</script>

<style lang="less" scoped>
  .action-icon {
    margin-left: 12px;
    cursor: pointer;
  }
</style>
