/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* Model */
export interface Model {
  object_arr?: {
    id?: number;
    name?: string;
  }[];
}

/* GET /descriptions/index/object-array */
export interface GetResponse {
  model: Model;
}
export function get(id: string) {
  return axios.get<GetResponse>(`/descriptions/index/object-array`);
}
