/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* Model */
export interface Model {
  double?: number;
  int64?: number;
  boolTrue?: boolean;
  boolFalse?: boolean;
  string?: string;
  datetime?: string;
  image?: string;
  bool_optionals?: boolean;
  int64_optionals?: number;
  string_optionals?: string;
}

/* GET /descriptions/index/scalar */
export interface GetResponse {
  model: Model;
}
export function get(id: string) {
  return axios.get<GetResponse>(`/descriptions/index/scalar`);
}
