/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* FormModel */
export interface FormModel {
}

/* GET /albums/${id}/show/photos/${subid}/delete */
export interface GetResponse {
  form: FormModel;
}
export function get(id: string, subid: string) {
  return axios.get<GetResponse>(`/albums/${id}/show/photos/${subid}/delete`);
}

/* PUT /albums/${id}/show/photos/${subid}/delete */
export interface UpdateRequest {
  form: FormModel;
}
export interface UpdateResponse {
  form: FormModel;
}
export function update(id: string, subid: string, req: UpdateRequest) {
  return axios.put<UpdateResponse>(`/albums/${id}/show/photos/${subid}/delete`, req);
}
