/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* Model */
export interface Model {
  id: string;
  title: string;
  url: string;
  thumbnailUrl: string;
}

/* GET /albums/${id}/show/photos */
export interface ListResponse {
  collection: Model[];
}
export function list(id: string) {
  return axios.get<ListResponse>(`/albums/${id}/show/photos`);
}
