/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* Model */
export interface Model {
  userId?: number;
  title?: string;
}

/* GET /albums/${id}/show/self */
export interface GetResponse {
  model: Model;
}
export function get(id: string) {
  return axios.get<GetResponse>(`/albums/${id}/show/self`);
}
