/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'AlbumsIndex',
    path: 'albums',
    component: () => import('@/views/modules/albums/index/index.vue'),
    meta: {
      authority: ['*', ],
      cache: true,
      title: 'albums--index.title',
    },
  },
  {
    name: 'AlbumsShow',
    path: 'albums/:id',
    component: () => import('@/views/modules/albums/show/index.vue'),
    meta: {
      authority: ['*', ],
      cache: false,
      title: 'albums--show.title',
    },
  },
  {
    name: 'AlbumsShowPhotos',
    path: 'albums/:id/show-photos',
    component: () => import('@/views/modules/albums/show-photos/index.vue'),
    meta: {
      authority: ['*', ],
      cache: false,
      title: 'albums--show-photos.title',
    },
  },
];

export default routes;
