/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'ChartsIndex',
    path: 'charts',
    component: () => import('@/views/modules/charts/index/index.vue'),
    meta: {
      authority: ['*', ],
      cache: true,
      title: 'charts--index.title',
    },
  },
];

export default routes;
