/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'comments--index',
    path: 'comments',
    component: () => import('@/views/modules/comments/index/index.vue'),
    meta: {
      authority: ['*', ],
    },
  },
];

export default routes;
