/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'DashboardWorkplace',
    path: 'dashboard/workplace',
    component: () => import('@/views/modules/dashboard/workplace/index.vue'),
    meta: {
      authority: ['*', ],
      cache: false,
      title: 'dashboard--workplace.title',
    },
  },
];

export default routes;
