/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'photos--index',
    path: 'photos',
    component: () => import('@/views/modules/photos/index/index.vue'),
    meta: {
      authority: ['*', ],
      title: 'photos--index.title',
    },
  },
];

export default routes;
