/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'posts--index',
    path: 'posts',
    component: () => import('@/views/modules/posts/index/index.vue'),
    meta: {
      authority: ['*'],
    },
  },
];

export default routes;
