/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'PostsIndex',
    path: 'posts',
    component: () => import('@/views/modules/posts/index/index.vue'),
    meta: {
      authority: ['*', ],
      cache: true,
      title: 'posts--index.title',
    },
  },
  {
    name: 'PostsShow',
    path: 'posts/:id',
    component: () => import('@/views/modules/posts/show/index.vue'),
    meta: {
      authority: ['*', ],
      cache: false,
      title: 'posts--show.title',
    },
  },
];

export default routes;
