/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'TablesIndex',
    path: 'tables',
    component: () => import('@/views/modules/tables/index/index.vue'),
    meta: {
      authority: ['*', ],
      cache: true,
      title: 'tables--index.title',
    },
  },
];

export default routes;
