/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'todos--index',
    path: 'todos',
    component: () => import('@/views/modules/todos/index/index.vue'),
    meta: {
      authority: ['*', ],
    },
  },
];

export default routes;
