/* Code generated by DullAdmin; DO NOT EDIT. */

import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'UsersIndex',
    path: 'users',
    component: () => import('@/views/modules/users/index/index.vue'),
    meta: {
      authority: ['*', ],
      cache: true,
      title: 'users--index.title',
    },
  },
  {
    name: 'UsersShow',
    path: 'users/:id',
    component: () => import('@/views/modules/users/show/index.vue'),
    meta: {
      authority: ['*', ],
      cache: false,
      title: 'users--show.title',
    },
  },
];

export default routes;
