<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('comments--show.self-block.title')" class="da-descriptions-block dac-self-block">
      <a-spin style="display: block" :loading="loading">
        <div class="arco-descriptions arco-descriptions-size-medium arco-descriptions-border">
          <div class="arco-descriptions-body">
            <table class="arco-descriptions-table">
              <tbody>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('comments--show.self-block.model.attributes.postId') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.postId"
                      :meta="modelMetadata['postId']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('comments--show.self-block.model.attributes.name') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.name"
                      :meta="modelMetadata['name']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('comments--show.self-block.model.attributes.email') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.email"
                      :meta="modelMetadata['email']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td class="arco-descriptions-item-label arco-descriptions-item-label-block">
                    {{ $t('comments--show.self-block.model.attributes.body') }}
                  </td>
                  <td class="arco-descriptions-item-value arco-descriptions-item-value-block">
                    <DullData
                      :data="store.body"
                      :meta="modelMetadata['body']"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import type { DescData } from '@arco-design/web-vue/es/descriptions/interface';
  import { Model, get } from '@/api/modules/comments/show/self-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Desc = DescData & { dataIndex: string };

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    postId: {
      type: 'int64',
      i18nKey: 'comments--show.self-block.model.attributes.postId',
    },
    name: {
      type: 'string',
      i18nKey: 'comments--show.self-block.model.attributes.name',
    },
    email: {
      type: 'string',
      i18nKey: 'comments--show.self-block.model.attributes.email',
    },
    body: {
      type: 'string',
      i18nKey: 'comments--show.self-block.model.attributes.body',
    },
  };

  // descriptions - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    postId: undefined,
    name: undefined,
    email: undefined,
    body: undefined,
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;

      if (model) {
        store.value = model;
      }
    } finally {
      setLoading(false);
    }
  };

  // descriptions - refresh
  const onDescriptionsRefresh = async () => {
    await fetchStore();
  };

  // descriptions - tabbable
  useTabbableViewBlock({
    viewName: 'CommentsShow',
    refreshFn: onDescriptionsRefresh,
  });

  // descriptions - init
  onDescriptionsRefresh();
</script>
