_role_optionals: &_role_optionals
  - 'admin'
  - 'user'

name: 'administrators'
authority: ['admin']
views:
  index:
    table:
      items:
        - { name: 'id', type: 'int64' }
        - { name: 'name', type: 'string' }
        - { name: 'role', type: 'string', optionals: *_role_optionals }
      searchers:
        - { name: 'id', predicate: 'eq' }
        - { name: 'role', predicate: 'eq' }

  show:
    descriptions:
      items:
        - { name: 'name', type: 'string' }
        - { name: 'role', type: 'string', optionals: *_role_optionals }

  new:
    form:
      items:
        - { name: 'name', type: 'string' }
        - { name: 'role', type: 'string', optionals: *_role_optionals }

  edit:
    form:
      items:
        - { name: 'name', type: 'string' }
        - { name: 'role', type: 'string', optionals: *_role_optionals }

  delete:
    form:
      items: []
