name: 'administrators'
authority: ['admin']
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'   , type: 'string' }
            - { name: 'name' , type: 'string' }
            - { name: 'role' , type: 'string', optionals: ["admin", "user"] }
          searchers:
            - { name: 'id'  , predicate: 'eq' }
            - { name: 'role', predicate: 'eq' }

  _from_items: &_form_items
    - { name: 'name' , type: 'string' }
    - { name: 'role' , type: 'string', optionals: ["admin", "user"] }
  new:
    blocks:
      - form:
          items: *_form_items
  edit:
    blocks:
      - form:
          items: *_form_items
