name: 'administrators'
authority: ['admin']
views:
  index:
    table:
      items:
        - { name: 'id'   , type: 'int64'  }
        - { name: 'name' , type: 'string' }
        - { name: 'role' , type: 'string', optionals: ["admin", "user"] }
      searchers:
        - { name: 'id'  , predicate: 'eq' }
        - { name: 'role', predicate: 'eq' }

  show:
    descriptions:
      items:
        - { name: 'name' , type: 'string' }
        - { name: 'role' , type: 'string', optionals: ["admin", "user"] }

  new:
    form:
      items:
        - { name: 'name' , type: 'string' }
        - { name: 'role' , type: 'string', optionals: ["admin", "user"] }

  edit:
    form:
      items:
        - { name: 'name' , type: 'string' }
        - { name: 'role' , type: 'string', optionals: ["admin", "user"] }

  delete:
    form:
      items: []
