name: 'administrators'
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'   , type: 'string' }
            - { name: 'name' , type: 'string' }
            - { name: 'role' , type: 'string' }
