name: 'administrators'
authority: ['admin']
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'   , type: 'string' }
            - { name: 'name' , type: 'string' }
            - { name: 'role' , type: 'string', optionals: ["admin", "user"] }
