name: 'albums'
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'    , type: 'int64'  }
            - { name: 'userId', type: 'int64'  }
            - { name: 'title' , type: 'string' }
          sorters:
            - { name: 'id', directions: ['ascend', 'descend'] }

  show:
    blocks:
      - descriptions:
          items:
            - { name: 'userId', type: 'int64'  }
            - { name: 'title' , type: 'string' }
      - relationship: 'embeds_many'
        name: 'photos'
        table:
          items:
            - { name: 'id'          , type: 'int64'  }
            - { name: 'title'       , type: 'string' }
            - { name: 'url'         , type: 'image'  }
            - { name: 'thumbnailUrl', type: 'image'  }
          pagination:
            per: 10
