name: 'albums'
views:
  index:
    table:
      items:
        - { name: 'id'    , type: 'int64'  }
        - { name: 'userId', type: 'int64'  }
        - { name: 'title' , type: 'string' }
      sorters:
        - { name: 'id', directions: ['ascend', 'descend'] }

  show:
    blocks:
      - descriptions:
          items:
            - { name: 'userId', type: 'int64'  }
            - { name: 'title' , type: 'string' }
      - relationship: 'embeds_many'
        name: 'photos'
        table:
          items:
            - { name: 'id'          , type: 'int64'  }
            - { name: 'title'       , type: 'string' }
            - { name: 'url'         , type: 'image'  }
            - { name: 'thumbnailUrl', type: 'image'  }
          pagination:
            per: 10
          operations:
            show:
              descriptions:
                items:
                  - { name: 'title'       , type: 'string' }
                  - { name: 'url'         , type: 'image'  }
                  - { name: 'thumbnailUrl', type: 'image'  }
            new:
              form:
                items:
                  - { name: 'title', type: 'string' }
            edit:
              form:
                items:
                  - { name: 'title', type: 'string' }
            delete:
              form:
                items: []

  ~show_photos:
    table:
      items:
        - { name: 'id'          , type: 'int64'  }
        - { name: 'title'       , type: 'string' }
        - { name: 'url'         , type: 'image'  }
        - { name: 'thumbnailUrl', type: 'image'  }
