name: 'albums'
views:
  index:
    blocks:
      - relationship: 'self'
        table:
          items:
            - name: 'userId'
              type: 'string'
            - name: 'id'
              type: 'string'
            - name: 'title'
              type: 'string'

  show:
    blocks:
      - relationship: 'self'
        descriptions:
          items:
            - name: 'userId'
              type: 'string'
            - name: 'id'
              type: 'string'
            - name: 'title'
              type: 'string'
      - relationship: 'embeds_many'
        name: 'photos'
        table:
          items:
            - name: 'id'
              type: 'string'
            - name: 'title'
              type: 'string'
            - name: 'url'
              type: 'string'
            - name: 'thumbnailUrl'
              type: 'string'
