name: 'charts'
views:
  index:
    blocks:
      - name: 'basic_line'
        echarts: {}
      - name: 'stacked_line'
        echarts: {}
      - name: 'waterfall'
        echarts: {}
      - name: 'bar_chart_on_polar'
        echarts: {}
      - name: 'pie_rich_text'
        echarts: {}
      - name: 'funnel_align'
        echarts: {}
    grid:
      items:
        - name: 'basic_line'
          span: { xs: 24, sm: 8 }
        - name: 'stacked_line'
          span: { xs: 24, sm: 8 }
        - name: 'waterfall'
          span: { xs: 24, sm: 8 }
        - name: 'funnel_align'
          span: 24
        - name: 'bar_chart_on_polar'
          span: { xs: 24, sm: 12 }
        - name: 'pie_rich_text'
          span: { xs: 24, sm: 12 }
