name: 'charts'
views:
  index:
    blocks:
      - relationship: 'embeds_one'
        name: 'basic_line'
        echarts: {}
      - relationship: 'embeds_one'
        name: 'stacked_line'
        echarts: {}
    grid:
      items:
        - name: 'basic_line'
          span: { xs: 24, sm: 12 }
        - name: 'stacked_line'
          span: { xs: 24, sm: 12 }
