name: 'comments'
views:
  index:
    blocks:
      - relationship: 'self'
        table:
          items:
            - name: 'postId'
              type: 'string'
            - name: 'id'
              type: 'string'
            - name: 'name'
              type: 'string'
            - name: 'email'
              type: 'string'
            - name: 'body'
              type: 'string'
