name: 'photos'
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'          , type: 'string' }
            - { name: 'albumId'     , type: 'string' }
            - { name: 'title'       , type: 'string' }
            - { name: 'url'         , type: 'string' }
            - { name: 'thumbnailUrl', type: 'string' }
