name: 'posts'
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'    , type: 'int64'  }
            - { name: 'userId', type: 'int64'  }
            - { name: 'title' , type: 'string' }
            - { name: 'body'  , type: 'string' }
          sorters:
            - { name: 'id', directions: ['ascend', 'descend'] }

  show:
    blocks:
      - descriptions:
          items:
            - { name: 'userId', type: 'int64'  }
            - { name: 'title' , type: 'string' }
            - { name: 'body'  , type: 'string' }
