name: 'posts'
views:
  index:
    blocks:
      - relationship: 'self'
        table:
          items:
            - name: 'id'
              type: 'string'
            - name: 'userId'
              type: 'string'
            - name: 'title'
              type: 'string'
            - name: 'body'
              type: 'string'
