name: 'posts'
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'    , type: 'string' }
            - { name: 'userId', type: 'string' }
            - { name: 'title' , type: 'string' }
            - { name: 'body'  , type: 'string' }
