name: 'todos'
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'       , type: 'string' }
            - { name: 'userId'   , type: 'string' }
            - { name: 'title'    , type: 'string' }
            - { name: 'completed', type: 'bool'  , optionals: [true, false] }
          sorters:
            - { name: 'id', directions: ['ascend', 'descend'] }
          searchers:
            - { name: 'userId'   , predicate: 'eq' }
            - { name: 'completed', predicate: 'eq' }

  new:
    blocks:
      - form:
          items:
            - { name: 'userId'   , type: 'string' }
            - { name: 'title'    , type: 'string' }
            - { name: 'completed', type: 'bool'   }

  edit:
    blocks:
      - form:
          items:
            - { name: 'userId'     , type: 'string' }
            - { name: 'title'      , type: 'string', hidden: true }
            - { name: 'completed'  , type: 'bool'   }
