name: 'todos'
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'       , type: 'string' }
            - { name: 'userId'   , type: 'string' }
            - { name: 'title'    , type: 'string' }
            - { name: 'completed', type: 'bool'   }
          sorters:
            - { name: 'id', directions: ['ascend', 'descend'] }
