name: 'todos'
views:
  index:
    table:
      items:
        - { name: 'id'       , type: 'int64'  }
        - { name: 'userId'   , type: 'int64'  }
        - { name: 'title'    , type: 'string' }
        - { name: 'completed', type: 'bool'  , optionals: [true, false] }
      sorters:
        - { name: 'id', directions: ['ascend', 'descend'] }
      searchers:
        - { name: 'userId'   , predicate: 'eq' }
        - { name: 'completed', predicate: 'eq' }
      operations:
        ~show_title:
          descriptions:
            items:
              - { name: 'title', type: 'string' }
        ~edit_title:
          form:
            items:
              - { name: 'title', type: 'string' }
        ~create_completed:
          form:
            items: []
        ~delete_completed:
          form:
            items: []

  show:
    descriptions:
      items:
        - { name: 'userId'   , type: 'int64'  }
        - { name: 'title'    , type: 'string' }
        - { name: 'completed', type: 'bool'  , optionals: [true, false] }

  new:
    form:
      items:
        - { name: 'userId'   , type: 'int64'  }
        - { name: 'title'    , type: 'string' }
        - { name: 'completed', type: 'bool'   }

  edit:
    form:
      items:
        - { name: 'userId'     , type: 'int64' }
        - { name: 'title'      , type: 'string', hidden: true }
        - { name: 'completed'  , type: 'bool'  }

  delete:
    authority: ['admin']
    form:
      items: []
