name: 'todos'
views:
  index:
    blocks:
      - table:
          items:
            - { name: 'id'       , type: 'string' }
            - { name: 'userId'   , type: 'string' }
            - { name: 'title'    , type: 'string' }
            - { name: 'completed', type: 'bool'  , optionals: [true, false] }
          sorters:
            - { name: 'id', directions: ['ascend', 'descend'] }
          searchers:
            - { name: 'userId'   , predicate: 'eq' }
            - { name: 'completed', predicate: 'eq' }

  _from_items: &_form_items
    - { name: 'userId'   , type: 'string' }
    - { name: 'title'    , type: 'string' }
    - { name: 'completed', type: 'bool'   }
  new:
    blocks:
      - form:
          items: *_form_items
  edit:
    blocks:
      - form:
          items: *_form_items
