name: 'users'
views:
  index:
    blocks:
      - table:
          _items_address: &_items_address
            - { name: 'street' , type: 'string' }
            - { name: 'suite'  , type: 'string' }
            - { name: 'city'   , type: 'string' }
            - { name: 'zipcode', type: 'string' }
            - { name: 'geo'    , type: 'string' }
          _items_company: &_items_company
            - { name: 'name'       , type: 'string' }
            - { name: 'catchPhrase', type: 'string' }
            - { name: 'bs'         , type: 'string' }
          items:
            - { name: 'id'      , type: 'string' }
            - { name: 'name'    , type: 'string' }
            - { name: 'username', type: 'string' }
            - { name: 'email'   , type: 'string' }
            - { name: 'address' , type: 'object', attributes: *_items_address }
            - { name: 'phone'   , type: 'string' }
            - { name: 'website' , type: 'string' }
            - { name: 'company' , type: 'object', attributes: *_items_company }
          sorters:
            - { name: 'id'      , directions: ['descend', 'ascend'] }
            - { name: 'name'    , directions: ['descend']           }
            - { name: 'username', directions: ['ascend', 'descend'] }
            - { name: 'email'   , directions: ['ascend']            }
