name: 'users'
views:
  index:
    table:
      items:
        - { name: 'id', type: 'int64' }
        - { name: 'name', type: 'string' }
        - { name: 'username', type: 'string' }
        - { name: 'avatar', type: 'image' }
        - { name: 'email', type: 'string' }
        - { name: 'phone', type: 'string' }
        - { name: 'website', type: 'string' }
      sorters:
        - { name: 'id', directions: ['descend', 'ascend'] }
      searchers:
        - { name: 'id', predicate: 'eq' }
        - { name: 'name', predicate: 'cont' }

  show:
    descriptions:
      items:
        - { name: 'id', type: 'int64' }
        - { name: 'name', type: 'string' }
        - { name: 'username', type: 'string' }
        - { name: 'avatar', type: 'image' }
        - { name: 'email', type: 'string' }
        - { name: 'phone', type: 'string' }
        - { name: 'website', type: 'string' }

  new:
    form:
      items:
        - { name: 'name', type: 'string' }
        - { name: 'username', type: 'string' }
        - { name: 'avatar', type: 'image' }
        - { name: 'email', type: 'string' }
        - { name: 'phone', type: 'string' }
        - { name: 'website', type: 'string' }

  edit:
    form:
      items:
        - { name: 'name', type: 'string' }
        - { name: 'username', type: 'string' }
        - { name: 'avatar', type: 'image' }
        - { name: 'email', type: 'string' }
        - { name: 'phone', type: 'string' }
        - { name: 'website', type: 'string' }

  delete:
    form:
      items: []
