<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('users--delete.self-block.title')" class="da-form-block dac-self-block">
      <a-spin style="display: block" :loading="loading">
        <a-form :model="store" :auto-label-width="true">
          <a-form-item>
            <a-space>
              <a-button
                type="primary"
                status="danger"
                :loading="saving"
                @click="onFormSave"
              >
                <template #icon>
                  <icon-save />
                </template>
                {{ $t('form.actions.delete') }}
              </a-button>
            </a-space>
          </a-form-item>
        </a-form>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref } from 'vue';
  import { useRouter, useRoute } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { omitBy } from 'lodash';
  import { Message } from '@arco-design/web-vue';
  import { FormModel, UpdateRequest, get, update } from '@/api/modules/users/delete/self-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';
  import { useAppStore } from '@/store';

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
  };

  // form - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<FormModel>({
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const _ = null;
    } finally {
      setLoading(false);
    }
  };

  // form - save
  const appStore = useAppStore();
  const { loading: saving, setLoading: setSaving } = useLoading(false);
  const onFormSave = async () => {
    setSaving(true);
    try {
      const req = {
        form: omitBy(store.value, (v) => {
          return v == null
        }),
      } as UpdateRequest;
      const { data } = await update(id, req);
      const { form } = data;

      if (form) {
        store.value = form;
      }

      Message.success(t('form.actions.delete.success'));

      const { back } = route.query;
      if (back) {
        appStore.removeCurrentActiveTab();
        appStore.setNewTabOpenParams({ refresh: true });
        router.replace({ path: back as string });
      }
    } finally {
      setSaving(false);
    }
  };

  // form - refresh
  const onFormRefresh = async () => {
    await fetchStore();
  };

  // form - tabbable
  useTabbableViewBlock({
    viewName: 'UsersDelete',
    refreshFn: onFormRefresh,
  });

  // form - init
  onFormRefresh();
</script>
