<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('tables--index.scalar-array-block.title')" class="da-table-block dac-scalar-array-block">
      <a-row class="da-table-block-toolbar">
        <!-- Table Collection Operations -->
        <a-col :span="12">
          <a-space>
          </a-space>
        </a-col>

        <!-- Table Search/Refresh/ColumnsSetting -->
        <a-col class="da-table-block-toolbar-r" :span="12">
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-btn" @click="onTableRefresh">
              <icon-refresh size="18"/>
            </div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-btn"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div v-for="(item, index) in tableColumnsWithShow" :key="item.dataIndex">
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="handleTableColumnsShowChange($event, item as TableColumnData, index)"
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>

      <!-- Table -->
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
      >
        <template #double_arr="{ record, column }">
          <DullList
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #int64_arr="{ record, column }">
          <DullList
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #string_arr="{ record, column }">
          <DullList
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #datetime_arr="{ record, column }">
          <DullList
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #image_arr="{ record, column }">
          <DullList
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #string_optionals_arr="{ record, column }">
          <DullList
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <!-- Table Model Operations -->
        <template #tableOperationsColumn="{ record, column }">
          <a-space>
          </a-space>
        </template>
      </a-table>
    </a-card>

    <!-- Table Model Operations UI indicator -->
    <div v-show="false" ref="tableOperationsColumnRenderableRef">
    </div>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch, onMounted } from 'vue';
  import { useRouter, useRoute, RouteLocationRaw } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/tables/index/scalar-array-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Column = TableColumnData & { show?: boolean, renderable?: boolean, hidden?: boolean };
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    double_arr: {
      type: 'double',
      i18nKey: 'tables--index.scalar-array-block.model.attributes.double_arr',
    },
    int64_arr: {
      type: 'int64',
      i18nKey: 'tables--index.scalar-array-block.model.attributes.int64_arr',
    },
    string_arr: {
      type: 'string',
      i18nKey: 'tables--index.scalar-array-block.model.attributes.string_arr',
    },
    datetime_arr: {
      type: 'datetime',
      i18nKey: 'tables--index.scalar-array-block.model.attributes.datetime_arr',
    },
    image_arr: {
      type: 'image',
      i18nKey: 'tables--index.scalar-array-block.model.attributes.image_arr',
    },
    string_optionals_arr: {
      type: 'string',
      i18nKey: 'tables--index.scalar-array-block.model.attributes.string_optionals_arr',
      optionals: {
        str: {
          i18nKey: 'tables--index.scalar-array-block.model.attributes.string_optionals_arr.optionals.str',
        },
      },
    },
  };

  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    total: 0,
    showTotal: true,
    hideOnSinglePage: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithConfiguration = ref<Record<string, Column>>({
    double_arr: {
      renderable: true,
    },
    int64_arr: {
      renderable: true,
    },
    string_arr: {
      renderable: true,
    },
    datetime_arr: {
      renderable: true,
    },
    image_arr: {
      renderable: true,
    },
    string_optionals_arr: {
      renderable: true,
    },
    tableOperationsColumn: {
      renderable: true,
    },
  });
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => {
    return ([
      {
        title: t('tables--index.scalar-array-block.model.attributes.double_arr'),
        dataIndex: 'double_arr',
        slotName: 'double_arr',
        cellClass: 'column-double_arr',
        hidden: false,
      },
      {
        title: t('tables--index.scalar-array-block.model.attributes.int64_arr'),
        dataIndex: 'int64_arr',
        slotName: 'int64_arr',
        cellClass: 'column-int64_arr',
        hidden: false,
      },
      {
        title: t('tables--index.scalar-array-block.model.attributes.string_arr'),
        dataIndex: 'string_arr',
        slotName: 'string_arr',
        cellClass: 'column-string_arr',
        hidden: false,
      },
      {
        title: t('tables--index.scalar-array-block.model.attributes.datetime_arr'),
        dataIndex: 'datetime_arr',
        slotName: 'datetime_arr',
        cellClass: 'column-datetime_arr',
        hidden: false,
      },
      {
        title: t('tables--index.scalar-array-block.model.attributes.image_arr'),
        dataIndex: 'image_arr',
        slotName: 'image_arr',
        cellClass: 'column-image_arr',
        hidden: false,
      },
      {
        title: t('tables--index.scalar-array-block.model.attributes.string_optionals_arr'),
        dataIndex: 'string_optionals_arr',
        slotName: 'string_optionals_arr',
        cellClass: 'column-string_optionals_arr',
        hidden: false,
      },
      {
        title: t('table.columns.operations'),
        dataIndex: 'tableOperationsColumn',
        slotName: 'tableOperationsColumn',
        cellClass: 'column-operations',
      },
    ] as Column[]).filter((item) => {
      return tableColumnsWithConfiguration.value[item.dataIndex as string].renderable;
    });
  });
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = !item.hidden;
      });
      tableColumnsShow.value = tableColumnsWithShow.value.filter(
        (item) => item.show
      );
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    tableColumnsShow.value = tableColumnsWithShow.value.filter(
      (item) => item.show
    );
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;

      if (collection) {
        store.value = collection;
      }

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = baseTablePagination.total;;
      }
    } finally {
      setLoading(false);
    }
  };
  const updateStore = (data: Record<string, any>) => {
    const { model } = data;
    if (model) {
      const foundIndex = -1
      if (foundIndex !== -1) {
        store.value.splice(foundIndex, 1, model);
      }
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - operations ui
  const tableOperationsColumnRenderableRef = ref();
  const tableOperationsColumnMoreRenderable = ref<boolean>(true);
  onMounted(() => {
    const el = tableOperationsColumnRenderableRef.value as any;
    if (el.children.length === 0) {
      tableColumnsWithConfiguration.value.tableOperationsColumn.renderable = false
    }
    if (el.querySelectorAll('.custom').length === 0) {
      tableOperationsColumnMoreRenderable.value = false
    }
  });

  // table - operations - goto
  const goto = (_route: Record<string, any>) => {
    router.push({ name: _route.name, params: _route.params, query: { back: route.path } });
  };

  // table - tabbable
  useTabbableViewBlock({
    viewName: 'TablesIndex',
    refreshFn: onTableRefresh,
  });

  // table - init
  onTableRefresh();
</script>
