<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('todos--edit.self-block.title')">
      <a-spin style="display: block" :loading="loading">
        <a-form
          :model="store"
          :auto-label-width="true"
        >
          <DullFormItem
            v-model="store.userId"
            :meta="modelMetadata.userId"
          />
          <DullFormItem
            v-model="store.title"
            :meta="modelMetadata.title"
          />
          <DullFormItem
            v-model="store.completed"
            :meta="modelMetadata.completed"
          />
          <a-form-item>
            <a-space>
              <a-button type="primary" @click="onFormSave" :loading="saving">
                <template #icon>
                  <icon-save />
                </template>
                {{ $t('form.actions.save') }}
              </a-button>
            </a-space>
          </a-form-item>
        </a-form>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref } from 'vue';
  import { useRoute } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { omitBy } from 'lodash';
  import { Message } from '@arco-design/web-vue';
  import { Model, UpdateRequest, get, update } from '@/api/modules/todos/edit/self';
  import { useLoading } from '@/hooks';

  // i18n
  const { t } = useI18n();

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    userId: {
      type: 'string',
      i18nKey: 'todos--edit.self-block.model.attributes.userId',
    },
    title: {
      type: 'string',
      i18nKey: 'todos--edit.self-block.model.attributes.title',
    },
    completed: {
      type: 'bool',
      i18nKey: 'todos--edit.self-block.model.attributes.completed',
    },
  };

  // form - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    userId: undefined,
    title: undefined,
    completed: undefined,
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;

      if (model) {
        store.value = model;
      }
    } finally {
      setLoading(false);
    }
  };

  // form - save
  const { loading: saving, setLoading: setSaving } = useLoading(false);
  const onFormSave = async () => {
    setSaving(true);
    try {
      const req = {
        model: omitBy(store.value, (v) => {
          return v == null
        }),
      } as UpdateRequest;
      const { data } = await update(id, req);
      const { model } = data;

      if (model) {
        store.value = model;
      }

      Message.success(t('form.actions.save.success'));
    } finally {
      setSaving(false);
    }
  };

  // form - init
  fetchStore();
</script>

<style lang="less" scoped></style>
