/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* Model */
export interface Model {
  albumId?: number;
  title?: string;
  url?: string;
  thumbnailUrl?: string;
}

/* GET /photos/${id}/show/self */
export interface GetResponse {
  model: Model;
}
export function get(id: string) {
  return axios.get<GetResponse>(`/photos/${id}/show/self`);
}
