/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* Model */
export interface Model {
  name?: string;
  role?: string;
}

/* GET /administrators/${id}/edit/self */
export interface GetResponse {
  model: Model;
}
export function get(id: string) {
  return axios.get<GetResponse>(`/administrators/${id}/edit/self`);
}

/* PUT /administrators/${id}/edit/self */
export interface UpdateRequest {
  model: Model;
}
export interface UpdateResponse {
  model: Model;
}
export function update(id: string, req: UpdateRequest) {
  return axios.put<UpdateResponse>(`/administrators/${id}/edit/self`, req);
}
