<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('administrators--edit.self-block.title')">
      <a-spin style="display: block" :loading="loading">
        <a-form
          :model="store"
          :auto-label-width="true"
        >
          <DullFormItem
            v-model="store.name"
            :meta="modelMetadata.name"
          />
          <DullFormItem
            v-model="store.role"
            :meta="modelMetadata.role"
          />
          <a-form-item>
            <a-space>
              <a-button type="primary" @click="onFormSave">
                <template #icon>
                  <icon-save />
                </template>
                {{ $t('form.actions.save') }}
              </a-button>
            </a-space>
          </a-form-item>
        </a-form>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref } from 'vue';
  import { useRoute } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { omitBy } from 'lodash';
  import { Model, UpdateRequest, get, update } from '@/api/modules/administrators/edit/self';
  import { useLoading } from '@/hooks';

  // i18n
  const { t } = useI18n();

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    name: {
      type: 'string',
      i18nKey: 'administrators--edit.self-block.model.attributes.name',
    },
    role: {
      type: 'string',
      i18nKey: 'administrators--edit.self-block.model.attributes.role',
      optionals: {
        admin: {
          i18nKey: 'administrators--edit.self-block.model.attributes.role.optionals.admin',
        },
        user: {
          i18nKey: 'administrators--edit.self-block.model.attributes.role.optionals.user',
        },
      },
    },
  };

  // form - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    name: null,
    role: null,
  } as Model);
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;
      store.value = model;
    } catch (_) {
      // .
    } finally {
      setLoading(false);
    }
  };

  // form - save
  const { loading: saving, setLoading: setSaving } = useLoading(true);
  const onFormSave = async () => {
    setSaving(true);
    try {
      const req = {
        model: omitBy(store.value, (v) => {
          return v == null
        }) as unknown as Model,
      } as UpdateRequest;
      const { data } = await update(id, req);
      const { model } = data;
      store.value = model;
    } catch (_) {
      // .
    } finally {
      setSaving(false);
    }
  };

  // form - init
  fetchStore();
</script>

<style lang="less" scoped></style>
