<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('administrators--show.self-block.title')" class="dulladmin-descriptions-block">
      <a-spin style="display: block" :loading="loading">
        <div
          class="arco-descriptions arco-descriptions-size-medium arco-descriptions-border"
        >
          <div class="arco-descriptions-body">
            <table class="arco-descriptions-table">
              <tbody>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('administrators--show.self-block.model.attributes.name') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.name"
                      :meta="modelMetadata['name']"
                    />
                  </td>
                </tr>
                <tr class="arco-descriptions-row">
                  <td
                    class="arco-descriptions-item-label arco-descriptions-item-label-block"
                  >
                    {{ $t('administrators--show.self-block.model.attributes.role') }}
                  </td>
                  <td
                    class="arco-descriptions-item-value arco-descriptions-item-value-block"
                  >
                    <DullData
                      :data="store.role"
                      :meta="modelMetadata['role']"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import type { DescData } from '@arco-design/web-vue/es/descriptions/interface';
  import { Model, get } from '@/api/modules/administrators/show/self-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Desc = DescData & { dataIndex: string };

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    name: {
      type: 'string',
      i18nKey: 'administrators--show.self-block.model.attributes.name',
    },
    role: {
      type: 'string',
      i18nKey: 'administrators--show.self-block.model.attributes.role',
      optionals: {
        admin: {
          i18nKey: 'administrators--show.self-block.model.attributes.role.optionals.admin',
        },
        user: {
          i18nKey: 'administrators--show.self-block.model.attributes.role.optionals.user',
        },
      },
    },
  };

  // descriptions - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model>({
    name: undefined,
    role: undefined,
  });
  const fetchStore = async () => {
    setLoading(true);
    try {
      const { data } = await get(id);
      const { model } = data;

      if (model) {
        store.value = model;
      }
    } finally {
      setLoading(false);
    }
  };

  // descriptions - refresh
  const onDescriptionsRefresh = async () => {
    await fetchStore();
  };

  // descriptions - tabbable
  useTabbableViewBlock({
    viewName: 'AdministratorsShow',
    refreshFn: onDescriptionsRefresh,
  });

  // descriptions - init
  onDescriptionsRefresh();
</script>
