/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';

/* Model */
export interface Model {
  postId?: number;
  name?: string;
  email?: string;
  body?: string;
}

/* GET /comments/${id}/show/self */
export interface GetResponse {
  model: Model;
}
export function get(id: string) {
  return axios.get<GetResponse>(`/comments/${id}/show/self`);
}
