<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('users--index.self-block.title')">
      <a-row>
        <a-col>
          <a-form
            :model="tableSearch"
            :auto-label-width="true"
          >
            <SimpleFormItem
              v-model="tableSearch.id_eq"
              :meta="searchMetadata.id_eq"
            />
            <SimpleFormItem
              v-model="tableSearch.name_cont"
              :meta="searchMetadata.name_cont"
            />
          </a-form>
        </a-col>
      </a-row>
      <a-row style="margin-bottom: 16px">
        <a-col
          style="display: flex; align-items: center; justify-content: end"
          :span="24"
        >
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh"
              ><icon-refresh size="18"
            /></div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div
                    v-for="(item, index) in tableColumnsWithShow"
                    :key="item.dataIndex"
                  >
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="
                          handleTableColumnsShowChange(
                            $event,
                            item as TableColumnData,
                            index
                          )
                        "
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
        @sorter-change="onTableSorterChange"
      >
        <template #id="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #name="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #username="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #email="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #address="{ record, column }">
          <SimpleDescriptions
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #phone="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #website="{ record, column }">
          <SimpleData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #company="{ record, column }">
          <SimpleDescriptions
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
      </a-table>
    </a-card>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch } from 'vue';
  import { useRoute } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/users/index/self';
  import SimpleData from '@/components/renderer/data/simple-data.vue';
  import SimpleList from '@/components/renderer/data/simple-list.vue';
  import SimpleDescriptions from '@/components/renderer/data/simple-descriptions.vue';
  import SimpleTable from '@/components/renderer/data/simple-table.vue';
  import SimpleFormItem from '@/components/renderer/form-item/simple-form-item.vue';
  import { useLoading } from '@/hooks';
  import { defaultValue, isDefaultValue } from '@/utils/metadata';

  // types
  type Column = TableColumnData & { show?: true };
  type Search = Record<string, any>;
  type Sorter = Record<string, any>;
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.id',
    },
    name: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.name',
    },
    username: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.username',
    },
    email: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.email',
    },
    address: {
      street: {
        type: 'string',
        i18nKey: 'users--index.self-block.model.attributes.address.street',
      },
      suite: {
        type: 'string',
        i18nKey: 'users--index.self-block.model.attributes.address.suite',
      },
      city: {
        type: 'string',
        i18nKey: 'users--index.self-block.model.attributes.address.city',
      },
      zipcode: {
        type: 'string',
        i18nKey: 'users--index.self-block.model.attributes.address.zipcode',
      },
      geo: {
        type: 'string',
        i18nKey: 'users--index.self-block.model.attributes.address.geo',
      },
    },
    phone: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.phone',
    },
    website: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.website',
    },
    company: {
      name: {
        type: 'string',
        i18nKey: 'users--index.self-block.model.attributes.company.name',
      },
      catchPhrase: {
        type: 'string',
        i18nKey: 'users--index.self-block.model.attributes.company.catchPhrase',
      },
      bs: {
        type: 'string',
        i18nKey: 'users--index.self-block.model.attributes.company.bs',
      },
    },
  };

  // search
  const searchMetadata: { [key: string]: any } = {
    id_eq: {
      name: 'id_eq',
      type: 'string',
      i18nKey: 'users--index.self-block.searchers.id_eq',
    },
    name_cont: {
      name: 'name_cont',
      type: 'string',
      i18nKey: 'users--index.self-block.searchers.name_cont',
    },
  };
  const baseTableSearch: Search = {
    id_eq: defaultValue<string>(searchMetadata.id_eq),
    name_cont: defaultValue<string>(searchMetadata.name_cont),
  };
  const tableSearch = reactive({
    ...baseTableSearch,
  });
  const apiSearch = (search: Search): any => {
    const o = omitBy(search, (v) => isDefaultValue(v));
    return isEmpty(o) ? null : o;
  };

  // sorter
  const baseTableSorter: Sorter = {
    name: '',
    direction: '',
  };
  const tableSorter = reactive({
    ...baseTableSorter,
  });
  const apiSorter = (sorter: Sorter): any => {
    if (sorter.name === '') return null;
    return { name: sorter.name, direction: sorter.direction };
  };

  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    showTotal: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => [
    {
      title: t('users--index.self-block.model.attributes.id'),
      dataIndex: 'id',
      slotName: 'id',
      sortable: {
        sortDirections: ['descend', 'ascend', ],
        sorter: true,
      },
    },
    {
      title: t('users--index.self-block.model.attributes.name'),
      dataIndex: 'name',
      slotName: 'name',
      sortable: {
        sortDirections: ['descend', ],
        sorter: true,
      },
    },
    {
      title: t('users--index.self-block.model.attributes.username'),
      dataIndex: 'username',
      slotName: 'username',
      sortable: {
        sortDirections: ['ascend', 'descend', ],
        sorter: true,
      },
    },
    {
      title: t('users--index.self-block.model.attributes.email'),
      dataIndex: 'email',
      slotName: 'email',
      sortable: {
        sortDirections: ['ascend', ],
        sorter: true,
      },
    },
    {
      title: t('users--index.self-block.model.attributes.address'),
      dataIndex: 'address',
      slotName: 'address',
    },
    {
      title: t('users--index.self-block.model.attributes.phone'),
      dataIndex: 'phone',
      slotName: 'phone',
    },
    {
      title: t('users--index.self-block.model.attributes.website'),
      dataIndex: 'website',
      slotName: 'website',
    },
    {
      title: t('users--index.self-block.model.attributes.company'),
      dataIndex: 'company',
      slotName: 'company',
    },
  ]);
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = true;
      });
      tableColumnsShow.value = cloneDeep(tableColumnsWithShow.value);
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    if (checked) {
      tableColumnsShow.value.splice(index, 0, column);
    } else {
      tableColumnsShow.value = tableColumnsShow.value.filter(
        (item) => item.dataIndex !== column.dataIndex
      );
    }
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;
      store.value = collection;

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = null;
        tablePagination.hideOnSinglePage = true;
      }
    } catch (_) {
      // .
    } finally {
      setLoading(false);
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - sorterChange
  const onTableSorterChange = async (dataIndex: string, direction: string) => {
    if (direction) {
      tableSorter.name = dataIndex;
      tableSorter.direction = direction;
    } else {
      tableSorter.name = baseTableSorter.name;
      tableSorter.direction = baseTableSorter.direction;
    }
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - init
  onTableRefresh();
</script>

<style lang="less" scoped>
  .action-icon {
    margin-left: 12px;
    cursor: pointer;
  }
</style>
