<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div>
    <a-card :title="$t('users--index.self-block.title')" class="da-table-block dac-self-block">
      <a-row style="margin-bottom: 16px">
        <!-- Table Collection Operations -->
        <a-col :span="12">
          <a-space>
          </a-space>
        </a-col>

        <!-- Table Search/Refresh/ColumnsSetting -->
        <a-col style="display: flex; align-items: center; justify-content: end" :span="12">
          <a-space>
            <a-tag
              v-for="(value, name) in tableSearchCondition"
              :key="name"
              :visible="!!value"
              color="arcoblue"
              size="small"
              closable
              @close="handleSearchConditionClose(name as string)"
            >
              {{ t(searchMetadata[name]['i18nKey']) }}
              "{{ searchMetadata[name].optionals?.[value] ? t(searchMetadata[name].optionals[value]['i18nKey']) : value }}"
            </a-tag>
            <div
              v-show="tableSearchConditionCount"
              style="cursor: pointer"
              @click="handleSearchConditionClose('')"
            >
              <a-tag color="orangered" size="small">
                {{ t('table.actions.clearSearch') }}
              </a-tag>
            </div>
          </a-space>
          <a-tooltip :content="$t('table.actions.search')">
            <div class="action-icon" @click="handleSearchModalVisible">
              <a-badge
                color="arcoblue"
                dot
                :dot-style="{ width: '8px', height: '8px' }"
                :count="tableSearchConditionCount"
              >
                <icon-find-replace size="18"/>
              </a-badge>
            </div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.refresh')">
            <div class="action-icon" @click="onTableRefresh">
              <icon-refresh size="18"/>
            </div>
          </a-tooltip>
          <a-tooltip :content="$t('table.actions.columnSetting')">
            <a-popover trigger="click" position="bl">
              <div class="action-icon"><icon-settings size="18" /></div>
              <template #content>
                <div>
                  <div v-for="(item, index) in tableColumnsWithShow" :key="item.dataIndex">
                    <div>
                      <a-checkbox
                        v-model="item.show"
                        @change="handleTableColumnsShowChange($event, item as TableColumnData, index)"
                      >
                        {{ item.title }}
                      </a-checkbox>
                    </div>
                  </div>
                </div>
              </template>
            </a-popover>
          </a-tooltip>
        </a-col>
      </a-row>

      <!-- Table -->
      <a-table
        row-key="id"
        :loading="loading"
        :pagination="tablePagination"
        :columns="(tableColumnsShow as TableColumnData[])"
        :data="tableData"
        @page-change="onTablePageChange"
        @sorter-change="onTableSorterChange"
      >
        <template #id="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #name="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #username="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #email="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #address="{ record, column }">
          <DullDescriptions
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #phone="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #website="{ record, column }">
          <DullData
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <template #company="{ record, column }">
          <DullDescriptions
            :data="record[column.dataIndex]"
            :meta="modelMetadata[column.dataIndex]"
          />
        </template>
        <!-- Table Model Operations -->
        <template #tableOperationsColumn="{ record, column }">
          <a-space>
            <a-button
              type="outline"
              status="success"
              size="small"
              @click="goto({ name: 'UsersShow', params: { id: record.id } })"
            >
              {{ $t('table.actions.show') }}
            </a-button>
          </a-space>
        </template>
      </a-table>
    </a-card>

    <!-- Table Search -->
    <a-modal
      v-model:visible="searchModalVisible"
      class="da-form-dialog"
      :ok-text="$t('table.actions.search')"
      :on-before-ok="handleSearchModalBeforeOk"
      @cancel="handleSearchModalCancel"
    >
      <template #title>
        {{ $t('users--index.self-block.title') }}
        -
        {{ $t('table.actions.search') }}
      </template>
      <a-form :model="tableSearchForm" :auto-label-width="true">
        <DullFormItem
          v-model="tableSearchForm.id_eq"
          :meta="searchMetadata.id_eq"
        />
        <DullFormItem
          v-model="tableSearchForm.name_cont"
          :meta="searchMetadata.name_cont"
        />
      </a-form>
    </a-modal>

    <!-- Table Model Operations UI indicator -->
    <div v-show="false" ref="tableOperationsColumnRenderableRef">
      <span />
    </div>
  </div>
</template>

<script lang="ts" setup>
  import { computed, reactive, ref, watch, onMounted } from 'vue';
  import { useRouter, useRoute, RouteLocationRaw } from 'vue-router';
  import { useI18n } from 'vue-i18n';
  import { cloneDeep, omitBy, isEmpty } from 'lodash';
  import type { TableColumnData } from '@arco-design/web-vue/es/table/interface';
  import { Model, ListRequest, list } from '@/api/modules/users/index/self-block';
  import { useLoading, useTabbableViewBlock } from '@/hooks';

  // types
  type Column = TableColumnData & { show?: boolean, renderable?: boolean, hidden?: boolean };
  type Search = Record<string, any>;
  type Sorter = Record<string, any>;
  type Pagination = Record<string, any>;

  // i18n
  const { t } = useI18n();

  // route
  const router = useRouter();
  const route = useRoute();
  const id = (route.params.id as string) ?? '';

  // model
  const modelMetadata: { [key: string]: any } = {
    id: {
      type: 'int64',
      i18nKey: 'users--index.self-block.model.attributes.id',
    },
    name: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.name',
    },
    username: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.username',
    },
    email: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.email',
    },
    address: {
      type: 'object',
      attributes: {
        street: {
          type: 'string',
          i18nKey: 'users--index.self-block.model.attributes.address.street',
        },
        suite: {
          type: 'string',
          i18nKey: 'users--index.self-block.model.attributes.address.suite',
        },
        city: {
          type: 'string',
          i18nKey: 'users--index.self-block.model.attributes.address.city',
        },
        zipcode: {
          type: 'string',
          i18nKey: 'users--index.self-block.model.attributes.address.zipcode',
        },
        geo: {
          type: 'string',
          i18nKey: 'users--index.self-block.model.attributes.address.geo',
        },
      }
    },
    phone: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.phone',
    },
    website: {
      type: 'string',
      i18nKey: 'users--index.self-block.model.attributes.website',
    },
    company: {
      type: 'object',
      attributes: {
        name: {
          type: 'string',
          i18nKey: 'users--index.self-block.model.attributes.company.name',
        },
        catchPhrase: {
          type: 'string',
          i18nKey: 'users--index.self-block.model.attributes.company.catchPhrase',
        },
        bs: {
          type: 'string',
          i18nKey: 'users--index.self-block.model.attributes.company.bs',
        },
      }
    },
  };

  // search
  const searchMetadata: { [key: string]: any } = {
    id_eq: {
      name: 'id_eq',
      type: 'int64',
      i18nKey: 'users--index.self-block.searchers.id_eq',
    },
    name_cont: {
      name: 'name_cont',
      type: 'string',
      i18nKey: 'users--index.self-block.searchers.name_cont',
    },
  };
  const baseTableSearch: Search = {
    id_eq: null,
    name_cont: null,
  };
  const tableSearch = reactive({
    ...baseTableSearch,
  });
  const tableSearchForm = reactive({
    ...tableSearch,
  });
  const tableSearchCondition = reactive({
    ...tableSearch,
  });
  const tableSearchConditionCount = ref(0);
  const apiSearch = (search: Search): any => {
    const o = omitBy(search, (v, k) => {
      if (searchMetadata[k].optionals) return v == null || v === '';
      return v == null || v === '' || v === false;
    });
    Object.assign(tableSearchCondition, cloneDeep(baseTableSearch), cloneDeep(o));
    tableSearchConditionCount.value = Object.keys(o).length
    return isEmpty(o) ? null : o;
  };

  // sorter
  const baseTableSorter: Sorter = {
    name: '',
    direction: '',
  };
  const tableSorter = reactive({
    ...baseTableSorter,
  });
  const apiSorter = (sorter: Sorter): any => {
    if (sorter.name === '') return null;
    return { name: sorter.name, direction: sorter.direction };
  };

  // pagination
  const baseTablePagination: Pagination = {
    pageSize: 20,
    current: 1,
    total: 0,
    showTotal: true,
    hideOnSinglePage: true,
  };
  const tablePagination = reactive({
    ...baseTablePagination,
  });
  const apiPagination = (pagination: Pagination): any => {
    return {
      page_size: pagination.pageSize,
      current: pagination.current,
    };
  };

  // table - columns initialize
  const tableColumnsWithConfiguration = ref<Record<string, Column>>({
    id: {
      renderable: true,
    },
    name: {
      renderable: true,
    },
    username: {
      renderable: true,
    },
    email: {
      renderable: true,
    },
    address: {
      renderable: true,
    },
    phone: {
      renderable: true,
    },
    website: {
      renderable: true,
    },
    company: {
      renderable: true,
    },
    tableOperationsColumn: {
      renderable: true,
    },
  });
  const tableColumnsWithShow = ref<Column[]>([]);
  const tableColumnsShow = ref<Column[]>([]);
  const tableColumns = computed<Column[]>(() => {
    return ([
      {
        title: t('users--index.self-block.model.attributes.id'),
        dataIndex: 'id',
        slotName: 'id',
        sortable: {
          sortDirections: ['descend', 'ascend', ],
          sorter: true,
        },
        cellClass: 'column-id',
        hidden: false,
      },
      {
        title: t('users--index.self-block.model.attributes.name'),
        dataIndex: 'name',
        slotName: 'name',
        sortable: {
          sortDirections: ['descend', ],
          sorter: true,
        },
        cellClass: 'column-name',
        hidden: false,
      },
      {
        title: t('users--index.self-block.model.attributes.username'),
        dataIndex: 'username',
        slotName: 'username',
        sortable: {
          sortDirections: ['ascend', 'descend', ],
          sorter: true,
        },
        cellClass: 'column-username',
        hidden: false,
      },
      {
        title: t('users--index.self-block.model.attributes.email'),
        dataIndex: 'email',
        slotName: 'email',
        sortable: {
          sortDirections: ['ascend', ],
          sorter: true,
        },
        cellClass: 'column-email',
        hidden: false,
      },
      {
        title: t('users--index.self-block.model.attributes.address'),
        dataIndex: 'address',
        slotName: 'address',
        cellClass: 'column-address',
        hidden: true,
      },
      {
        title: t('users--index.self-block.model.attributes.phone'),
        dataIndex: 'phone',
        slotName: 'phone',
        cellClass: 'column-phone',
        hidden: false,
      },
      {
        title: t('users--index.self-block.model.attributes.website'),
        dataIndex: 'website',
        slotName: 'website',
        cellClass: 'column-website',
        hidden: false,
      },
      {
        title: t('users--index.self-block.model.attributes.company'),
        dataIndex: 'company',
        slotName: 'company',
        cellClass: 'column-company',
        hidden: true,
      },
      {
        title: t('table.columns.operations'),
        dataIndex: 'tableOperationsColumn',
        slotName: 'tableOperationsColumn',
        cellClass: 'column-operations',
      },
    ] as Column[]).filter((item) => {
      return tableColumnsWithConfiguration.value[item.dataIndex as string].renderable;
    });
  });
  watch(
    () => tableColumns.value,
    (val) => {
      tableColumnsWithShow.value = cloneDeep(val);
      tableColumnsWithShow.value.forEach((item) => {
        item.show = !item.hidden;
      });
      tableColumnsShow.value = tableColumnsWithShow.value.filter(
        (item) => item.show
      );
    },
    { deep: true, immediate: true }
  );

  // table - columns show/hide
  const handleTableColumnsShowChange = (
    checked: boolean | (string | boolean | number)[],
    column: Column,
    index: number
  ) => {
    tableColumnsShow.value = tableColumnsWithShow.value.filter(
      (item) => item.show
    );
  };

  // table - store
  const { loading, setLoading } = useLoading(true);
  const store = ref<Model[]>([]);
  const fetchStore = async (req: ListRequest) => {
    setLoading(true);
    try {
      const { data } = await list(id, req);
      const { collection, pagination } = data;

      if (collection) {
        store.value = collection;
      }

      if (pagination) {
        tablePagination.pageSize = pagination.page_size;
        tablePagination.current = pagination.current;
        tablePagination.total = pagination.total;
      } else {
        tablePagination.pageSize = baseTablePagination.pageSize;
        tablePagination.current = baseTablePagination.current;
        tablePagination.total = baseTablePagination.total;;
      }
    } finally {
      setLoading(false);
    }
  };
  const updateStore = (data: Record<string, any>) => {
    const { model } = data;
    if (model) {
      const foundIndex = store.value.findIndex((e) => String(e.id) === String(model.id));
      if (foundIndex !== -1) {
        store.value.splice(foundIndex, 1, model);
      }
    }
  };

  // table - data
  const tableData = computed(() => store.value);

  // table - refresh
  const onTableRefresh = async () => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - pageChange
  const onTablePageChange = async (current: number) => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: { ...apiPagination(tablePagination), current },
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - search
  const onTableSearch = async () => {
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(baseTablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - search condition
  const handleSearchConditionClose = async(name: string) => {
    if (name === '') {
      Object.assign(tableSearch, cloneDeep(baseTableSearch));
    } else {
      tableSearch[name] = null;
    }
    await onTableSearch();
  };

  // table - search modal
  const searchModalVisible = ref(false);
  const handleSearchModalVisible = () => {
    Object.assign(tableSearchForm, cloneDeep(tableSearch));
    searchModalVisible.value = true;
  };
  const handleSearchModalBeforeOk = async () => {
    Object.assign(tableSearch, cloneDeep(tableSearchForm));
    await onTableSearch();
    searchModalVisible.value = false;
  };
  const handleSearchModalCancel = () => {
    searchModalVisible.value = false;
  };

  // table - sorterChange
  const onTableSorterChange = async (dataIndex: string, direction: string) => {
    if (direction) {
      tableSorter.name = dataIndex;
      tableSorter.direction = direction;
    } else {
      tableSorter.name = baseTableSorter.name;
      tableSorter.direction = baseTableSorter.direction;
    }
    const req = omitBy({
      search: apiSearch(tableSearch),
      sorter: apiSorter(tableSorter),
      pagination: apiPagination(tablePagination),
    }, v => v == null) as ListRequest;
    await fetchStore(req);
  };

  // table - operations ui
  const tableOperationsColumnRenderableRef = ref();
  onMounted(() => {
    const el = tableOperationsColumnRenderableRef.value as any;
    if (el.children.length === 0) {
      tableColumnsWithConfiguration.value.tableOperationsColumn.renderable = false
    }
  });

  // table - operations - goto
  const goto = (_route: Record<string, any>) => {
    router.push({ name: _route.name, params: _route.params, query: { back: route.path } });
  };

  // table - tabbable
  useTabbableViewBlock({
    viewName: 'UsersIndex',
    refreshFn: onTableRefresh,
  });

  // table - init
  onTableRefresh();
</script>
