/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';
import {
  Pagination,
} from '@/api/common';

/* Model */
export interface Model {
  double?: number;
  int64?: number;
  bool?: boolean;
  string?: string;
  datetime?: string;
  image?: string;
  string_optionals?: string;
}

/* GET /tables/index/scalar */
export interface ListRequest {
  pagination: Pagination;
}
export interface ListResponse {
  collection: Model[];
  pagination?: Pagination;
}
export function list(id: string, req: ListRequest) {
  return axios.get<ListResponse>(`/tables/index/scalar`, { params: req });
}
