/* Code generated by DullAdmin; DO NOT EDIT. */

import axios from 'axios';
import {
  Pagination,
} from '@/api/common';

/* Model */
export interface Model {
  double_arr?: number[];
  int64_arr?: number[];
  string_arr?: string[];
  datetime_arr?: string[];
  image_arr?: string[];
  string_optionals_arr?: string[];
}

/* GET /tables/index/scalar-array */
export interface ListRequest {
  pagination: Pagination;
}
export interface ListResponse {
  collection: Model[];
  pagination?: Pagination;
}
export function list(id: string, req: ListRequest) {
  return axios.get<ListResponse>(`/tables/index/scalar-array`, { params: req });
}
