<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="da-view dac-photos-show-view">
    <a-grid class="da-view-grid" :cols='24' :col-gap="16" :row-gap="16">
      <a-grid-item class="da-view-grid-item dac-self-view-grid-item" :span='24'>
        <div>
          <SelfBlock />
        </div>
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import { useTabbableView } from '@/hooks';
  import SelfBlock from '@/views/modules/photos/show/components/self-block.vue';

  useTabbableView({
    name: 'PhotosShow',
  });
</script>

<script lang="ts">
  export default {
    name: 'PhotosShow',
  };
</script>
