<!-- Code generated by DullAdmin; DO NOT EDIT. -->

<template>
  <div class="dulladmin-view">
    <a-grid :cols="24" :row-gap="16">
      <a-grid-item :span="24">
        <div
        >
          <SelfBlock />
        </div>
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script lang="ts" setup>
  import { useTabbableView } from '@/hooks';
  import SelfBlock from '@/views/modules/photos/show/components/self-block.vue';

  useTabbableView({
    name: 'PhotosShow',
  });
</script>

<script lang="ts">
  export default {
    name: 'PhotosShow',
  };
</script>
